// Code generated by `axebom profile gen`. DO NOT EDIT.
//
// Source:  (profile aibom-operational-v1 revision 1)
// Regenerate: task profile:gen
//
// Editing this file is pointless — it is overwritten — and dangerous: the
// coverage checker reads the PROFILE at runtime, so a hand-edit here would
// drift from what actually scores a report.

package model

// AIBOMOperationalFieldsLabel is what a report calls this number.
//
// Carried as data so no renderer hardcodes the string and none can mislabel it.
const AIBOMOperationalFieldsLabel = "AI operational surface"

// Operational field ids for the aibom_operational set.
const (
	FieldAxebomAibomOps01ModelKey           = "axebom.aibom.ops.01.model_key"
	FieldAxebomAibomOps02IdentityConfidence = "axebom.aibom.ops.02.identity_confidence"
	FieldAxebomAibomOps03FoundBy            = "axebom.aibom.ops.03.found_by"
	FieldAxebomAibomOps04Evidence           = "axebom.aibom.ops.04.evidence"
	FieldAxebomAibomOps05Verified           = "axebom.aibom.ops.05.verified"
	FieldAxebomAibomOps06Frameworks         = "axebom.aibom.ops.06.frameworks"
	FieldAxebomAibomOps07Prompts            = "axebom.aibom.ops.07.prompts"
	FieldAxebomAibomOps08VectorStores       = "axebom.aibom.ops.08.vector_stores"
	FieldAxebomAibomOps09RagPipelines       = "axebom.aibom.ops.09.rag_pipelines"
	FieldAxebomAibomOps11AgentsAndTools     = "axebom.aibom.ops.11.agents_and_tools"
	FieldAxebomAibomOps12InferenceEndpoints = "axebom.aibom.ops.12.inference_endpoints"
	FieldAxebomAibomOps13EuAiActTier        = "axebom.aibom.ops.13.eu_ai_act_tier"
	FieldAxebomAibomOps14NistAiRmf          = "axebom.aibom.ops.14.nist_ai_rmf"
	FieldAxebomAibomOps15Iso42001           = "axebom.aibom.ops.15.iso_42001"
	FieldAxebomAibomOps16AttestationResult  = "axebom.aibom.ops.16.attestation_result"
)

// AIBOMOperationalFields are AxeBOM OPERATIONAL elements, not CERT-In ones.
//
// ⚠ THEY MUST NEVER MOVE completeness_pct OR declaration_pct. Those two numbers
// answer "how much of what CERT-In requires is present". These answer "how
// buildable and buyable is this parts list" — a different question with a
// different authority behind it. Merging them would let a customer's diligence
// about unit prices raise a percentage they hand to a regulator.
//
// Render the count from len(AIBOMOperationalFields) — never write the number.
var AIBOMOperationalFields = []ProfileField{
	{ID: FieldAxebomAibomOps01ModelKey, Ordinal: 0, Name: "Resolved identity", CanonicalPath: "ai_model.model_key", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps02IdentityConfidence, Ordinal: 0, Name: "Identity confidence", CanonicalPath: "ai_model.identity_confidence", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension", Values: []string{"high", "medium", "low"}},
	{ID: FieldAxebomAibomOps03FoundBy, Ordinal: 0, Name: "Discovering engines", CanonicalPath: "ai_model.found_by[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps04Evidence, Ordinal: 0, Name: "Source evidence", CanonicalPath: "ai_model.evidence[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps05Verified, Ordinal: 0, Name: "Upstream verification", CanonicalPath: "ai_model.verified", CycloneDXPath: "", SPDXPath: "", Type: "boolean", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps06Frameworks, Ordinal: 0, Name: "AI frameworks", CanonicalPath: "ai_model.dependencies[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps07Prompts, Ordinal: 0, Name: "Prompts", CanonicalPath: "ai_assets.prompt[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps08VectorStores, Ordinal: 0, Name: "Vector stores", CanonicalPath: "ai_assets.vector_store[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps09RagPipelines, Ordinal: 0, Name: "RAG pipelines", CanonicalPath: "ai_assets.rag_pipeline[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps11AgentsAndTools, Ordinal: 0, Name: "Agents", CanonicalPath: "ai_assets.agent[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps12InferenceEndpoints, Ordinal: 0, Name: "Inference services", CanonicalPath: "ai_assets.endpoint[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps13EuAiActTier, Ordinal: 0, Name: "EU AI Act risk tier", CanonicalPath: "ai_model.eu_ai_act_tier", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension", Values: []string{"unacceptable", "high", "limited", "minimal", "undetermined"}},
	{ID: FieldAxebomAibomOps14NistAiRmf, Ordinal: 0, Name: "NIST AI RMF functions", CanonicalPath: "ai_model.nist_ai_rmf[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps15Iso42001, Ordinal: 0, Name: "ISO/IEC 42001 controls", CanonicalPath: "ai_model.iso_42001[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomAibomOps16AttestationResult, Ordinal: 0, Name: "Attestation verification", CanonicalPath: "ai_model.attestation_verified", CycloneDXPath: "", SPDXPath: "", Type: "boolean", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
}
