// Code generated by `axebom profile gen`. DO NOT EDIT.
//
// Source: docs/reference/CERT-In_BOM_Guidelines_v2.0.pdf (profile certin-v2.0 revision 1)
// Regenerate: task profile:gen
//
// Editing this file is pointless — it is overwritten — and dangerous: the
// coverage checker reads the PROFILE at runtime, so a hand-edit here would
// drift from what actually scores a report.

package model

// ProfileField mirrors one entry in the compliance profile.
type ProfileField struct {
	ID            string
	Ordinal       int
	Name          string
	CanonicalPath string
	CycloneDXPath string
	SPDXPath      string
	Type          string
	Weight        int
	Required      bool
	Scored        bool
	SourcePage    int
	Status        string
	// Values is the closed set an enum field accepts, empty for every other
	// type.
	//
	// ⚠ IT WAS DROPPED BY THE GENERATOR, AND FOUR COPIES OF ONE SET GREW IN ITS
	// PLACE. The profile has always carried a values list — criticality's
	// [critical, high, medium, low] is transcribed verbatim from p.23 — but
	// nothing emitted it, so every consumer that needed an enum hardcoded it:
	// hbom.Criticalities, hbom.CriticalityValues, a sentence inside a
	// validation error, and workers/hbom/model.py CRITICALITY_VALUES. Two of
	// them had already drifted apart.
	Values []string
	// UserSupplied marks an element NO TOOL CAN REPORT — it describes intent or
	// policy rather than anything discoverable from code or a model card, so it
	// is collected from the operator.
	//
	// ⚠ IT LIVES IN THE PROFILE BECAUSE IT DRIFTED WHEN IT DID NOT. Go and
	// Python each kept their own list and disagreed by one element
	// (environmental_impact), so that element was reachable by no form and
	// populated by no tool — while a test asserted the Go list was complete.
	UserSupplied bool
}

// ProfileID identifies the standard these fields come from.
const ProfileID = "certin-v2.0"

// ProfileRevision is bumped whenever the profile changes.
const ProfileRevision = 1

// ProfileAllVerified reports whether every entry was transcribed from the
// source document. When false, reports must say so.
const ProfileAllVerified = true

// Field identifiers. Stable forever — referenced by tests,
// diagnostics and report anchors. Never renumber.
const (
	FieldCertinSbomPpFrequency                    = "certin.sbom.pp.frequency"
	FieldCertinSbomPpDepth                        = "certin.sbom.pp.depth"
	FieldCertinSbomPpKnownUnknowns                = "certin.sbom.pp.known_unknowns"
	FieldCertinSbomPpDistributionAndDelivery      = "certin.sbom.pp.distribution_and_delivery"
	FieldCertinSbomPpAccessControl                = "certin.sbom.pp.access_control"
	FieldCertinSbomPpAccommodationOfMistakes      = "certin.sbom.pp.accommodation_of_mistakes"
	FieldCertinSbom01ComponentName                = "certin.sbom.01.component_name"
	FieldCertinSbom02ComponentVersion             = "certin.sbom.02.component_version"
	FieldCertinSbom03ComponentDescription         = "certin.sbom.03.component_description"
	FieldCertinSbom04ComponentSupplier            = "certin.sbom.04.component_supplier"
	FieldCertinSbom05ComponentLicense             = "certin.sbom.05.component_license"
	FieldCertinSbom06ComponentOrigin              = "certin.sbom.06.component_origin"
	FieldCertinSbom07ComponentDependencies        = "certin.sbom.07.component_dependencies"
	FieldCertinSbom08Vulnerabilities              = "certin.sbom.08.vulnerabilities"
	FieldCertinSbom09PatchStatus                  = "certin.sbom.09.patch_status"
	FieldCertinSbom10ReleaseDate                  = "certin.sbom.10.release_date"
	FieldCertinSbom11EolDate                      = "certin.sbom.11.eol_date"
	FieldCertinSbom12Criticality                  = "certin.sbom.12.criticality"
	FieldCertinSbom13UsageRestrictions            = "certin.sbom.13.usage_restrictions"
	FieldCertinSbom14Checksums                    = "certin.sbom.14.checksums"
	FieldCertinSbom15Comments                     = "certin.sbom.15.comments"
	FieldCertinSbom16AuthorOfSbomData             = "certin.sbom.16.author_of_sbom_data"
	FieldCertinSbom17Timestamp                    = "certin.sbom.17.timestamp"
	FieldCertinSbom18ExecutableProperty           = "certin.sbom.18.executable_property"
	FieldCertinSbom19ArchiveProperty              = "certin.sbom.19.archive_property"
	FieldCertinSbom20StructuredProperty           = "certin.sbom.20.structured_property"
	FieldCertinSbom21UniqueIdentifier             = "certin.sbom.21.unique_identifier"
	FieldCertinQbom01ModelName                    = "certin.qbom.01.model_name"
	FieldCertinQbom02Version                      = "certin.qbom.02.version"
	FieldCertinQbom03VendorOrigin                 = "certin.qbom.03.vendor_origin"
	FieldCertinQbom04LicenseInformation           = "certin.qbom.04.license_information"
	FieldCertinQbom05CryptographicAsset           = "certin.qbom.05.cryptographic_asset"
	FieldCertinQbom06CommunicationProtocol        = "certin.qbom.06.communication_protocol"
	FieldCertinQbom07Hardware                     = "certin.qbom.07.hardware"
	FieldCertinQbom08SoftwareDependencies         = "certin.qbom.08.software_dependencies"
	FieldCertinQbom09EnvironmentalImpact          = "certin.qbom.09.environmental_impact"
	FieldCertinQbom10Vulnerabilities              = "certin.qbom.10.vulnerabilities"
	FieldCertinQbom11Attestations                 = "certin.qbom.11.attestations"
	FieldCertinCryptoAlgoName                     = "certin.crypto.algo.name"
	FieldCertinCryptoAlgoAssetType                = "certin.crypto.algo.asset_type"
	FieldCertinCryptoAlgoPrimitive                = "certin.crypto.algo.primitive"
	FieldCertinCryptoAlgoMode                     = "certin.crypto.algo.mode"
	FieldCertinCryptoAlgoCryptoFunctions          = "certin.crypto.algo.crypto_functions"
	FieldCertinCryptoAlgoSecurityLevel            = "certin.crypto.algo.security_level"
	FieldCertinCryptoAlgoOid                      = "certin.crypto.algo.oid"
	FieldCertinCryptoAlgoList                     = "certin.crypto.algo.list"
	FieldCertinCryptoCertName                     = "certin.crypto.cert.name"
	FieldCertinCryptoCertAssetType                = "certin.crypto.cert.asset_type"
	FieldCertinCryptoCertSubjectName              = "certin.crypto.cert.subject_name"
	FieldCertinCryptoCertIssuerName               = "certin.crypto.cert.issuer_name"
	FieldCertinCryptoCertNotValidBefore           = "certin.crypto.cert.not_valid_before"
	FieldCertinCryptoCertNotValidAfter            = "certin.crypto.cert.not_valid_after"
	FieldCertinCryptoCertSigAlgoRef               = "certin.crypto.cert.sig_algo_ref"
	FieldCertinCryptoCertSubjectPkRef             = "certin.crypto.cert.subject_pk_ref"
	FieldCertinCryptoCertFormat                   = "certin.crypto.cert.format"
	FieldCertinCryptoCertExtension                = "certin.crypto.cert.extension"
	FieldCertinCryptoKeyName                      = "certin.crypto.key.name"
	FieldCertinCryptoKeyAssetType                 = "certin.crypto.key.asset_type"
	FieldCertinCryptoKeyId                        = "certin.crypto.key.id"
	FieldCertinCryptoKeyState                     = "certin.crypto.key.state"
	FieldCertinCryptoKeySize                      = "certin.crypto.key.size"
	FieldCertinCryptoKeyCreationDate              = "certin.crypto.key.creation_date"
	FieldCertinCryptoKeyActivationDate            = "certin.crypto.key.activation_date"
	FieldCertinCryptoProtoName                    = "certin.crypto.proto.name"
	FieldCertinCryptoProtoAssetType               = "certin.crypto.proto.asset_type"
	FieldCertinCryptoProtoVersion                 = "certin.crypto.proto.version"
	FieldCertinCryptoProtoCipherSuites            = "certin.crypto.proto.cipher_suites"
	FieldCertinCryptoProtoOid                     = "certin.crypto.proto.oid"
	FieldAxebomCryptoQuantumVulnerable            = "axebom.crypto.quantum_vulnerable"
	FieldAxebomCryptoPqcRecommendation            = "axebom.crypto.pqc_recommendation"
	FieldAxebomCryptoDeprecationStatus            = "axebom.crypto.deprecation_status"
	FieldCertinAibom01ModelName                   = "certin.aibom.01.model_name"
	FieldCertinAibom02ModelVersion                = "certin.aibom.02.model_version"
	FieldCertinAibom03ModelType                   = "certin.aibom.03.model_type"
	FieldCertinAibom04ModelDeveloper              = "certin.aibom.04.model_developer"
	FieldCertinAibom05Licensing                   = "certin.aibom.05.licensing"
	FieldCertinAibom06SoftwareDependencies        = "certin.aibom.06.software_dependencies"
	FieldCertinAibom07MlModelsAlgorithms          = "certin.aibom.07.ml_models_algorithms"
	FieldCertinAibom08PerformanceMetrics          = "certin.aibom.08.performance_metrics"
	FieldCertinAibom09DataSource                  = "certin.aibom.09.data_source"
	FieldCertinAibom10DataSets                    = "certin.aibom.10.data_sets"
	FieldCertinAibom11Hardware                    = "certin.aibom.11.hardware"
	FieldCertinAibom12SecurityRequirements        = "certin.aibom.12.security_requirements"
	FieldCertinAibom13Input                       = "certin.aibom.13.input"
	FieldCertinAibom14Output                      = "certin.aibom.14.output"
	FieldCertinAibom15IntendedUsage               = "certin.aibom.15.intended_usage"
	FieldCertinAibom16OutOfScopeUsage             = "certin.aibom.16.out_of_scope_usage"
	FieldCertinAibom17EnvironmentalImpact         = "certin.aibom.17.environmental_impact"
	FieldCertinAibom18Vulnerabilities             = "certin.aibom.18.vulnerabilities"
	FieldCertinAibom19Attestations                = "certin.aibom.19.attestations"
	FieldAxebomAibomOwaspLlmTop10                 = "axebom.aibom.owasp_llm_top10"
	FieldAxebomAibomRiskScore                     = "axebom.aibom.risk_score"
	FieldCertinHbom01ProductName                  = "certin.hbom.01.product_name"
	FieldCertinHbom02ProductVersion               = "certin.hbom.02.product_version"
	FieldCertinHbom03ProductDetails               = "certin.hbom.03.product_details"
	FieldCertinHbom04WarrantyAmc                  = "certin.hbom.04.warranty_amc"
	FieldCertinHbom05ManufacturerName             = "certin.hbom.05.manufacturer_name"
	FieldCertinHbom06ManufacturerLocation         = "certin.hbom.06.manufacturer_location"
	FieldCertinHbom07ManufacturingDate            = "certin.hbom.07.manufacturing_date"
	FieldCertinHbom08SupplierInformation          = "certin.hbom.08.supplier_information"
	FieldCertinHbom09SupplierLocation             = "certin.hbom.09.supplier_location"
	FieldCertinHbom10ModelNumber                  = "certin.hbom.10.model_number"
	FieldCertinHbom11SerialNumber                 = "certin.hbom.11.serial_number"
	FieldCertinHbom12TechnicalSpecification       = "certin.hbom.12.technical_specification"
	FieldCertinHbom13ComponentSupplierInformation = "certin.hbom.13.component_supplier_information"
	FieldCertinHbom14ComponentSupplierLocation    = "certin.hbom.14.component_supplier_location"
	FieldCertinHbom15TechnologyNode               = "certin.hbom.15.technology_node"
	FieldCertinHbom16Compliance                   = "certin.hbom.16.compliance"
	FieldCertinHbom17PowerSupply                  = "certin.hbom.17.power_supply"
	FieldCertinHbom18LicenseInformation           = "certin.hbom.18.license_information"
	FieldCertinHbom19TestResult                   = "certin.hbom.19.test_result"
	FieldCertinHbom20SubComponent                 = "certin.hbom.20.sub_component"
	FieldCertinHbom21FirmwareVersion              = "certin.hbom.21.firmware_version"
	FieldCertinHbom22Origin                       = "certin.hbom.22.origin"
	FieldCertinHbom23Criticality                  = "certin.hbom.23.criticality"
	FieldCertinHbom24Vulnerabilities              = "certin.hbom.24.vulnerabilities"
	FieldCertinVexRemediation                     = "certin.vex.remediation"
	FieldCertinVexWorkarounds                     = "certin.vex.workarounds"
	FieldCertinVexDowntime                        = "certin.vex.downtime"
	FieldCertinVexJustification                   = "certin.vex.justification"
	FieldCertinCsafDescription                    = "certin.csaf.description"
	FieldCertinCsafAffectedVersions               = "certin.csaf.affected_versions"
	FieldCertinCsafSeverity                       = "certin.csaf.severity"
	FieldCertinCsafMitigation                     = "certin.csaf.mitigation"
	FieldCertinDist531Rbac                        = "certin.dist.5.3.1.rbac"
	FieldCertinDist532PublicPrivate               = "certin.dist.5.3.2.public_private"
	FieldCertinDist533Transport                   = "certin.dist.5.3.3.transport"
	FieldCertinDist534Automation                  = "certin.dist.5.3.4.automation"
	FieldCertinDist535Verification                = "certin.dist.5.3.5.verification"
	FieldCertinDist536Audit                       = "certin.dist.5.3.6.audit"
	FieldCertinDist537Incident                    = "certin.dist.5.3.7.incident"
)

// SBOMFields are the scored required elements for a SBOM.
//
// Render the count from len(SBOMFields) — never write the number.
var SBOMFields = []ProfileField{
	{ID: FieldCertinSbom01ComponentName, Ordinal: 1, Name: "Component Name", CanonicalPath: "component.name", CycloneDXPath: "components[].name", SPDXPath: "packages[].name", Type: "string", Weight: 3, Required: true, Scored: true, SourcePage: 22, Status: "verified"},
	{ID: FieldCertinSbom02ComponentVersion, Ordinal: 2, Name: "Component Version", CanonicalPath: "component.version_raw", CycloneDXPath: "components[].version", SPDXPath: "packages[].versionInfo", Type: "string", Weight: 3, Required: true, Scored: true, SourcePage: 22, Status: "verified"},
	{ID: FieldCertinSbom03ComponentDescription, Ordinal: 3, Name: "Component Description", CanonicalPath: "component.description", CycloneDXPath: "components[].description", SPDXPath: "packages[].description", Type: "text", Weight: 1, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom04ComponentSupplier, Ordinal: 4, Name: "Component Supplier", CanonicalPath: "component.supplier", CycloneDXPath: "components[].supplier.name", SPDXPath: "packages[].supplier", Type: "string", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom05ComponentLicense, Ordinal: 5, Name: "Component License", CanonicalPath: "component.license_effective", CycloneDXPath: "components[].licenses", SPDXPath: "packages[].licenseConcluded", Type: "spdx_expression", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom06ComponentOrigin, Ordinal: 6, Name: "Component Origin", CanonicalPath: "component.origin", CycloneDXPath: "components[].properties[axebom:origin]", SPDXPath: "packages[].originator", Type: "enum", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified", Values: []string{"proprietary", "open-source", "third-party-vendor", "unknown"}},
	{ID: FieldCertinSbom07ComponentDependencies, Ordinal: 7, Name: "Component Dependencies", CanonicalPath: "component.dependencies[]", CycloneDXPath: "dependencies[]", SPDXPath: "relationships[DEPENDS_ON]", Type: "ref_list", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom08Vulnerabilities, Ordinal: 8, Name: "Vulnerabilities", CanonicalPath: "component.findings[]", CycloneDXPath: "vulnerabilities[]", SPDXPath: "relationships[HAS_ASSOCIATED_VULNERABILITY]", Type: "ref_list", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom09PatchStatus, Ordinal: 9, Name: "Patch Status", CanonicalPath: "component.patch_status", CycloneDXPath: "components[].properties[axebom:patch_status]", SPDXPath: "annotations[]", Type: "enum", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified", Values: []string{"up-to-date", "patch-available", "no-fix-available", "unknown"}},
	{ID: FieldCertinSbom10ReleaseDate, Ordinal: 10, Name: "Release Date", CanonicalPath: "component.release_date", CycloneDXPath: "components[].properties[axebom:release_date]", SPDXPath: "packages[].releaseDate", Type: "date", Weight: 1, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom11EolDate, Ordinal: 11, Name: "End-of-Life (EOL) Date", CanonicalPath: "component.eol_date", CycloneDXPath: "components[].properties[axebom:eol_date]", SPDXPath: "packages[].validUntilDate", Type: "date", Weight: 1, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom12Criticality, Ordinal: 12, Name: "Criticality", CanonicalPath: "component.criticality", CycloneDXPath: "components[].properties[axebom:criticality]", SPDXPath: "annotations[]", Type: "enum", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified", Values: []string{"critical", "high", "medium", "low"}},
	{ID: FieldCertinSbom13UsageRestrictions, Ordinal: 13, Name: "Usage Restrictions", CanonicalPath: "component.usage_restrictions", CycloneDXPath: "components[].properties[axebom:usage_restrictions]", SPDXPath: "packages[].comment", Type: "text", Weight: 1, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom14Checksums, Ordinal: 14, Name: "Checksums or Hashes", CanonicalPath: "component.hashes[]", CycloneDXPath: "components[].hashes[]", SPDXPath: "packages[].checksums[]", Type: "hash_list", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom15Comments, Ordinal: 15, Name: "Comments or Notes", CanonicalPath: "component.comments", CycloneDXPath: "components[].properties[axebom:comments]", SPDXPath: "packages[].comment", Type: "text", Weight: 1, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom16AuthorOfSbomData, Ordinal: 16, Name: "Author of SBOM Data", CanonicalPath: "component.provenance[].author", CycloneDXPath: "metadata.authors[]", SPDXPath: "creationInfo.creators[]", Type: "string", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom17Timestamp, Ordinal: 17, Name: "Timestamp", CanonicalPath: "bom_document.generated_at", CycloneDXPath: "metadata.timestamp", SPDXPath: "creationInfo.created", Type: "datetime", Weight: 3, Required: true, Scored: true, SourcePage: 23, Status: "verified"},
	{ID: FieldCertinSbom18ExecutableProperty, Ordinal: 18, Name: "Executable Property", CanonicalPath: "component.executable_property", CycloneDXPath: "components[].properties[axebom:executable]", SPDXPath: "packages[].primaryPackagePurpose", Type: "tristate", Weight: 1, Required: true, Scored: true, SourcePage: 24, Status: "verified"},
	{ID: FieldCertinSbom19ArchiveProperty, Ordinal: 19, Name: "Archive Property", CanonicalPath: "component.archive_property", CycloneDXPath: "components[].properties[axebom:archive]", SPDXPath: "packages[].packageFileName", Type: "tristate", Weight: 1, Required: true, Scored: true, SourcePage: 24, Status: "verified"},
	{ID: FieldCertinSbom20StructuredProperty, Ordinal: 20, Name: "Structured Property", CanonicalPath: "component.structured_property", CycloneDXPath: "components[].properties[axebom:structured]", SPDXPath: "annotations[]", Type: "tristate", Weight: 1, Required: true, Scored: true, SourcePage: 24, Status: "verified"},
	{ID: FieldCertinSbom21UniqueIdentifier, Ordinal: 21, Name: "Unique Identifier", CanonicalPath: "component.certin_identifier", CycloneDXPath: "components[].properties[axebom:certin_id]", SPDXPath: "packages[].externalRefs[PACKAGE-MANAGER/purl]", Type: "string", Weight: 3, Required: true, Scored: true, SourcePage: 24, Status: "verified"},
}

// QBOMFields are the scored required elements for a QBOM.
//
// Render the count from len(QBOMFields) — never write the number.
var QBOMFields = []ProfileField{
	{ID: FieldCertinQbom01ModelName, Ordinal: 0, Name: "Model Name", CanonicalPath: "quantum_component.model_name", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 44, Status: "verified"},
	{ID: FieldCertinQbom02Version, Ordinal: 0, Name: "Version", CanonicalPath: "quantum_component.version", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 44, Status: "verified"},
	{ID: FieldCertinQbom03VendorOrigin, Ordinal: 0, Name: "Vendor & Origin Information", CanonicalPath: "quantum_component.vendor_origin", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 44, Status: "verified"},
	{ID: FieldCertinQbom04LicenseInformation, Ordinal: 0, Name: "License Information", CanonicalPath: "quantum_component.license_info", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 44, Status: "verified"},
	{ID: FieldCertinQbom05CryptographicAsset, Ordinal: 0, Name: "Cryptographic Asset", CanonicalPath: "quantum_component.crypto_assets[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 44, Status: "verified"},
	{ID: FieldCertinQbom06CommunicationProtocol, Ordinal: 0, Name: "Communication Protocol", CanonicalPath: "quantum_component.communication_protocol", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
	{ID: FieldCertinQbom07Hardware, Ordinal: 0, Name: "Hardware", CanonicalPath: "quantum_component.hardware", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
	{ID: FieldCertinQbom08SoftwareDependencies, Ordinal: 0, Name: "Software Dependencies", CanonicalPath: "quantum_component.software_dependencies", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
	{ID: FieldCertinQbom09EnvironmentalImpact, Ordinal: 0, Name: "Environmental Impact", CanonicalPath: "quantum_component.environmental_impact", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
	{ID: FieldCertinQbom10Vulnerabilities, Ordinal: 0, Name: "Vulnerabilities", CanonicalPath: "quantum_component.findings[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
	{ID: FieldCertinQbom11Attestations, Ordinal: 0, Name: "Attestations", CanonicalPath: "quantum_component.attestation_signature", CycloneDXPath: "", SPDXPath: "", Type: "signature", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
}

// AIBOMFields are the scored required elements for a AIBOM.
//
// Render the count from len(AIBOMFields) — never write the number.
var AIBOMFields = []ProfileField{
	{ID: FieldCertinAibom01ModelName, Ordinal: 0, Name: "Model Name", CanonicalPath: "ai_model.model_name", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom02ModelVersion, Ordinal: 0, Name: "Model Version", CanonicalPath: "ai_model.model_version", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom03ModelType, Ordinal: 0, Name: "Model Type", CanonicalPath: "ai_model.model_type", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom04ModelDeveloper, Ordinal: 0, Name: "Model Developer", CanonicalPath: "ai_model.model_developer", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom05Licensing, Ordinal: 0, Name: "Model Licensing Information", CanonicalPath: "ai_model.licensing", CycloneDXPath: "", SPDXPath: "", Type: "spdx_expression", Weight: 3, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom06SoftwareDependencies, Ordinal: 0, Name: "Software Dependencies", CanonicalPath: "ai_model.software_dependencies[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom07MlModelsAlgorithms, Ordinal: 0, Name: "ML Models and Algorithms", CanonicalPath: "ai_model.ml_models_algorithms[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 3, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom08PerformanceMetrics, Ordinal: 0, Name: "Model Performance Metrics", CanonicalPath: "ai_model.performance_metrics", CycloneDXPath: "", SPDXPath: "", Type: "json", Weight: 1, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom09DataSource, Ordinal: 0, Name: "Data Source", CanonicalPath: "ai_model.data_source", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 54, Status: "verified"},
	{ID: FieldCertinAibom10DataSets, Ordinal: 0, Name: "Data Sets", CanonicalPath: "ai_model.data_sets[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 55, Status: "verified"},
	{ID: FieldCertinAibom11Hardware, Ordinal: 0, Name: "Hardware", CanonicalPath: "ai_model.hardware", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 55, Status: "verified"},
	{ID: FieldCertinAibom12SecurityRequirements, Ordinal: 0, Name: "Security Requirements", CanonicalPath: "ai_model.security_requirements", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 55, Status: "verified", UserSupplied: true},
	{ID: FieldCertinAibom13Input, Ordinal: 0, Name: "Input", CanonicalPath: "ai_model.input", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 55, Status: "verified"},
	{ID: FieldCertinAibom14Output, Ordinal: 0, Name: "Output", CanonicalPath: "ai_model.output", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 55, Status: "verified"},
	{ID: FieldCertinAibom15IntendedUsage, Ordinal: 0, Name: "Intended Usage", CanonicalPath: "ai_model.intended_usage", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 55, Status: "verified", UserSupplied: true},
	{ID: FieldCertinAibom16OutOfScopeUsage, Ordinal: 0, Name: "Out of Scope Usage", CanonicalPath: "ai_model.out_of_scope_usage", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 55, Status: "verified", UserSupplied: true},
	{ID: FieldCertinAibom17EnvironmentalImpact, Ordinal: 0, Name: "Environmental Impact", CanonicalPath: "ai_model.environmental_impact", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 55, Status: "verified", UserSupplied: true},
	{ID: FieldCertinAibom18Vulnerabilities, Ordinal: 0, Name: "Vulnerabilities", CanonicalPath: "ai_model.findings[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 55, Status: "verified"},
	{ID: FieldCertinAibom19Attestations, Ordinal: 0, Name: "Attestations", CanonicalPath: "ai_model.attestation_signature", CycloneDXPath: "", SPDXPath: "", Type: "signature", Weight: 3, Required: false, Scored: true, SourcePage: 55, Status: "verified", UserSupplied: true},
}

// HBOMFields are the scored required elements for a HBOM.
//
// Render the count from len(HBOMFields) — never write the number.
var HBOMFields = []ProfileField{
	{ID: FieldCertinHbom01ProductName, Ordinal: 0, Name: "Product Name", CanonicalPath: "hardware_component.product_name", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 60, Status: "verified"},
	{ID: FieldCertinHbom02ProductVersion, Ordinal: 0, Name: "Product Version", CanonicalPath: "hardware_component.product_version", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 60, Status: "verified"},
	{ID: FieldCertinHbom03ProductDetails, Ordinal: 0, Name: "Product Details", CanonicalPath: "hardware_component.product_details", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 60, Status: "verified"},
	{ID: FieldCertinHbom04WarrantyAmc, Ordinal: 0, Name: "Warranty/AMC", CanonicalPath: "hardware_component.warranty_amc", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 60, Status: "verified"},
	{ID: FieldCertinHbom05ManufacturerName, Ordinal: 0, Name: "Manufacturer Name", CanonicalPath: "hardware_component.manufacturer_name", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 60, Status: "verified"},
	{ID: FieldCertinHbom06ManufacturerLocation, Ordinal: 0, Name: "Manufacturer Location", CanonicalPath: "hardware_component.manufacturer_location", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 60, Status: "verified"},
	{ID: FieldCertinHbom07ManufacturingDate, Ordinal: 0, Name: "Manufacturing Date", CanonicalPath: "hardware_component.manufacturing_date", CycloneDXPath: "", SPDXPath: "", Type: "date", Weight: 1, Required: false, Scored: true, SourcePage: 60, Status: "verified"},
	{ID: FieldCertinHbom08SupplierInformation, Ordinal: 0, Name: "Supplier Information", CanonicalPath: "hardware_component.supplier_info", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom09SupplierLocation, Ordinal: 0, Name: "Supplier Location", CanonicalPath: "hardware_component.supplier_location", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom10ModelNumber, Ordinal: 0, Name: "Model Number", CanonicalPath: "hardware_component.model_number", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom11SerialNumber, Ordinal: 0, Name: "Serial Number", CanonicalPath: "hardware_component.serial_number", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom12TechnicalSpecification, Ordinal: 0, Name: "Technical Specification", CanonicalPath: "hardware_component.technical_specification", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom13ComponentSupplierInformation, Ordinal: 0, Name: "Supplier Information (component)", CanonicalPath: "hardware_component.component_supplier_info", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom14ComponentSupplierLocation, Ordinal: 0, Name: "Supplier Location (component)", CanonicalPath: "hardware_component.component_supplier_location", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom15TechnologyNode, Ordinal: 0, Name: "Technology Node", CanonicalPath: "hardware_component.technology_node", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 1, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom16Compliance, Ordinal: 0, Name: "Compliance", CanonicalPath: "hardware_component.compliance[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom17PowerSupply, Ordinal: 0, Name: "Power supply", CanonicalPath: "hardware_component.power_supply", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom18LicenseInformation, Ordinal: 0, Name: "License Information", CanonicalPath: "hardware_component.license_info", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom19TestResult, Ordinal: 0, Name: "Test Result", CanonicalPath: "hardware_component.test_result", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom20SubComponent, Ordinal: 0, Name: "Sub-component", CanonicalPath: "hardware_component.children[]", CycloneDXPath: "", SPDXPath: "", Type: "recursive_ref", Weight: 3, Required: false, Scored: true, SourcePage: 61, Status: "verified"},
	{ID: FieldCertinHbom21FirmwareVersion, Ordinal: 0, Name: "Firmware Version", CanonicalPath: "hardware_component.firmware_version", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 62, Status: "verified"},
	{ID: FieldCertinHbom22Origin, Ordinal: 0, Name: "Origin", CanonicalPath: "hardware_component.origin", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 62, Status: "verified"},
	{ID: FieldCertinHbom23Criticality, Ordinal: 0, Name: "Criticality Rating", CanonicalPath: "hardware_component.criticality", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 62, Status: "verified", Values: []string{"critical", "high", "medium", "low"}},
	{ID: FieldCertinHbom24Vulnerabilities, Ordinal: 0, Name: "Vulnerabilities", CanonicalPath: "hardware_component.findings[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 62, Status: "verified"},
}

// CryptoFieldsByAssetType is TYPE-DISCRIMINATED (CERT-In Table 9).
//
// The four asset types have DIFFERENT field sets. Coverage must be scored
// against the set for the row's asset_type: scoring a certificate against
// key_size would report every CBOM at roughly 30% coverage — falsely, in a
// document shown to a regulator.
var CryptoFieldsByAssetType = map[string][]ProfileField{
	"algorithm": {
		{ID: FieldCertinCryptoAlgoName, Ordinal: 0, Name: "Name", CanonicalPath: "crypto_asset.name", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
		{ID: FieldCertinCryptoAlgoAssetType, Ordinal: 0, Name: "Asset Type", CanonicalPath: "crypto_asset.asset_type", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified", Values: []string{"algorithm"}},
		{ID: FieldCertinCryptoAlgoPrimitive, Ordinal: 0, Name: "Primitive", CanonicalPath: "crypto_asset.primitive", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
		{ID: FieldCertinCryptoAlgoMode, Ordinal: 0, Name: "Mode", CanonicalPath: "crypto_asset.mode", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 45, Status: "verified"},
		{ID: FieldCertinCryptoAlgoCryptoFunctions, Ordinal: 0, Name: "Crypto Functions", CanonicalPath: "crypto_asset.crypto_functions[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
		{ID: FieldCertinCryptoAlgoSecurityLevel, Ordinal: 0, Name: "Classical security level", CanonicalPath: "crypto_asset.classical_security_level", CycloneDXPath: "", SPDXPath: "", Type: "integer", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
		{ID: FieldCertinCryptoAlgoOid, Ordinal: 0, Name: "OID", CanonicalPath: "crypto_asset.oid", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
		{ID: FieldCertinCryptoAlgoList, Ordinal: 0, Name: "List", CanonicalPath: "crypto_asset.algorithm_list[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 1, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
	},
	"certificate": {
		{ID: FieldCertinCryptoCertName, Ordinal: 0, Name: "Name", CanonicalPath: "crypto_asset.name", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoCertAssetType, Ordinal: 0, Name: "Asset Type", CanonicalPath: "crypto_asset.asset_type", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified", Values: []string{"certificate"}},
		{ID: FieldCertinCryptoCertSubjectName, Ordinal: 0, Name: "Subject Name", CanonicalPath: "crypto_asset.cert_subject", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoCertIssuerName, Ordinal: 0, Name: "Issuer Name", CanonicalPath: "crypto_asset.cert_issuer", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoCertNotValidBefore, Ordinal: 0, Name: "Not Valid Before", CanonicalPath: "crypto_asset.not_valid_before", CycloneDXPath: "", SPDXPath: "", Type: "datetime", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoCertNotValidAfter, Ordinal: 0, Name: "Not Valid After", CanonicalPath: "crypto_asset.not_valid_after", CycloneDXPath: "", SPDXPath: "", Type: "datetime", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoCertSigAlgoRef, Ordinal: 0, Name: "Signature Algorithm Reference", CanonicalPath: "crypto_asset.signature_algo_ref", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoCertSubjectPkRef, Ordinal: 0, Name: "Subject Public Key Reference", CanonicalPath: "crypto_asset.subject_public_key_ref", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoCertFormat, Ordinal: 0, Name: "Certificate Format", CanonicalPath: "crypto_asset.cert_format", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 1, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoCertExtension, Ordinal: 0, Name: "Certificate Extension", CanonicalPath: "crypto_asset.cert_extension", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 1, Required: false, Scored: true, SourcePage: 48, Status: "verified"},
	},
	"key": {
		{ID: FieldCertinCryptoKeyName, Ordinal: 0, Name: "Name", CanonicalPath: "crypto_asset.name", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
		{ID: FieldCertinCryptoKeyAssetType, Ordinal: 0, Name: "Asset Type", CanonicalPath: "crypto_asset.asset_type", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified", Values: []string{"key"}},
		{ID: FieldCertinCryptoKeyId, Ordinal: 0, Name: "id", CanonicalPath: "crypto_asset.key_id", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
		{ID: FieldCertinCryptoKeyState, Ordinal: 0, Name: "state", CanonicalPath: "crypto_asset.key_state", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified", Values: []string{"active", "revoked", "expired", "unknown"}},
		{ID: FieldCertinCryptoKeySize, Ordinal: 0, Name: "size", CanonicalPath: "crypto_asset.key_size", CycloneDXPath: "", SPDXPath: "", Type: "integer", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
		{ID: FieldCertinCryptoKeyCreationDate, Ordinal: 0, Name: "Creation Date", CanonicalPath: "crypto_asset.creation_date", CycloneDXPath: "", SPDXPath: "", Type: "date", Weight: 1, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
		{ID: FieldCertinCryptoKeyActivationDate, Ordinal: 0, Name: "Activation Date", CanonicalPath: "crypto_asset.activation_date", CycloneDXPath: "", SPDXPath: "", Type: "date", Weight: 1, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
	},
	"protocol": {
		{ID: FieldCertinCryptoProtoName, Ordinal: 0, Name: "Name", CanonicalPath: "crypto_asset.name", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 46, Status: "verified"},
		{ID: FieldCertinCryptoProtoAssetType, Ordinal: 0, Name: "Asset Type", CanonicalPath: "crypto_asset.asset_type", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified", Values: []string{"protocol"}},
		{ID: FieldCertinCryptoProtoVersion, Ordinal: 0, Name: "Version", CanonicalPath: "crypto_asset.protocol_version", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoProtoCipherSuites, Ordinal: 0, Name: "Cipher Suites", CanonicalPath: "crypto_asset.cipher_suites[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 3, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
		{ID: FieldCertinCryptoProtoOid, Ordinal: 0, Name: "OID", CanonicalPath: "crypto_asset.oid", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 1, Required: false, Scored: true, SourcePage: 47, Status: "verified"},
	},
}

// PracticeFields are CERT-In Table 5 category 3 — per-PROJECT settings,
// not a report section. Implementing only the data fields and claiming
// CERT-In compliance is overstating.
var PracticeFields = []ProfileField{
	{ID: FieldCertinSbomPpFrequency, Ordinal: 0, Name: "Frequency", CanonicalPath: "", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "verified"},
	{ID: FieldCertinSbomPpDepth, Ordinal: 0, Name: "Depth", CanonicalPath: "", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "verified"},
	{ID: FieldCertinSbomPpKnownUnknowns, Ordinal: 0, Name: "Known Unknowns", CanonicalPath: "", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "verified"},
	{ID: FieldCertinSbomPpDistributionAndDelivery, Ordinal: 0, Name: "Distribution and Delivery", CanonicalPath: "", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "verified"},
	{ID: FieldCertinSbomPpAccessControl, Ordinal: 0, Name: "Access Control", CanonicalPath: "", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "verified", Values: []string{"public", "private"}},
	{ID: FieldCertinSbomPpAccommodationOfMistakes, Ordinal: 0, Name: "Accommodation of Mistakes", CanonicalPath: "", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "verified"},
}

// VEXFields are CERT-In §6's per-statement fields (p.35) — scored over
// findings that have an effective VEX statement, not over every finding.
var VEXFields = []ProfileField{
	{ID: FieldCertinVexRemediation, Ordinal: 0, Name: "Remediation", CanonicalPath: "vex_statement.remediation", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 35, Status: "verified"},
	{ID: FieldCertinVexWorkarounds, Ordinal: 0, Name: "Workarounds", CanonicalPath: "vex_statement.workarounds", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 35, Status: "verified"},
	{ID: FieldCertinVexDowntime, Ordinal: 0, Name: "Restart/Downtime Required", CanonicalPath: "vex_statement.downtime", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 35, Status: "verified"},
	{ID: FieldCertinVexJustification, Ordinal: 0, Name: "Justification", CanonicalPath: "vex_statement.justification", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 35, Status: "verified"},
}

// CSAFFields are CERT-In §6's per-advisory required content (p.35) —
// scored over findings whose winning VEX statement has a generated CSAF
// advisory.
var CSAFFields = []ProfileField{
	{ID: FieldCertinCsafDescription, Ordinal: 0, Name: "Description", CanonicalPath: "csaf_advisory.description", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 35, Status: "verified"},
	{ID: FieldCertinCsafAffectedVersions, Ordinal: 0, Name: "Affected Product Versions", CanonicalPath: "csaf_advisory.affected_versions[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 35, Status: "verified"},
	{ID: FieldCertinCsafSeverity, Ordinal: 0, Name: "Severity Assessment", CanonicalPath: "csaf_advisory.severity", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 35, Status: "verified"},
	{ID: FieldCertinCsafMitigation, Ordinal: 0, Name: "Recommended Mitigation Steps", CanonicalPath: "csaf_advisory.mitigation_steps", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 3, Required: false, Scored: true, SourcePage: 35, Status: "verified"},
}

// BOMLevels are BOM depth levels (CERT-In §3.1).
var BOMLevels = []string{
	"top_level",
	"n_level",
	"delivery",
	"transitive",
	"complete",
}

// SDLCClassifications are SDLC stages (CERT-In §3.2).
var SDLCClassifications = []string{
	"design",
	"source",
	"build",
	"analyzed",
	"deployed",
	"runtime",
}

// VEXStatuses are The four VEX statuses (CERT-In §6).
var VEXStatuses = []string{
	"not_affected",
	"affected",
	"fixed",
	"under_investigation",
}
