// Code generated by `axebom profile gen`. DO NOT EDIT.
//
// Source:  (profile hbom-manufacturing-v1 revision 1)
// Regenerate: task profile:gen
//
// Editing this file is pointless — it is overwritten — and dangerous: the
// coverage checker reads the PROFILE at runtime, so a hand-edit here would
// drift from what actually scores a report.

package model

// HBOMManufacturingFieldsLabel is what a report calls this number.
//
// Carried as data so no renderer hardcodes the string and none can mislabel it.
const HBOMManufacturingFieldsLabel = "Manufacturing and procurement readiness"

// Operational field ids for the hbom_manufacturing set.
const (
	FieldAxebomHbomMfg01Designators       = "axebom.hbom.mfg.01.designators"
	FieldAxebomHbomMfg02PackageFootprint  = "axebom.hbom.mfg.02.package_footprint"
	FieldAxebomHbomMfg03Quantity          = "axebom.hbom.mfg.03.quantity"
	FieldAxebomHbomMfg04Description       = "axebom.hbom.mfg.04.description"
	FieldAxebomHbomMfg05SupplierSku       = "axebom.hbom.mfg.05.supplier_sku"
	FieldAxebomHbomMfg06PreferredSupplier = "axebom.hbom.mfg.06.preferred_supplier"
	FieldAxebomHbomMfg07Alternates        = "axebom.hbom.mfg.07.alternates"
	FieldAxebomHbomMfg08UnitPrice         = "axebom.hbom.mfg.08.unit_price"
	FieldAxebomHbomMfg09Currency          = "axebom.hbom.mfg.09.currency"
	FieldAxebomHbomMfg10DoNotPopulate     = "axebom.hbom.mfg.10.do_not_populate"
	FieldAxebomHbomMfg11AssemblyType      = "axebom.hbom.mfg.11.assembly_type"
	FieldAxebomHbomMfg12LifecycleStatus   = "axebom.hbom.mfg.12.lifecycle_status"
)

// HBOMManufacturingFields are AxeBOM OPERATIONAL elements, not CERT-In ones.
//
// ⚠ THEY MUST NEVER MOVE completeness_pct OR declaration_pct. Those two numbers
// answer "how much of what CERT-In requires is present". These answer "how
// buildable and buyable is this parts list" — a different question with a
// different authority behind it. Merging them would let a customer's diligence
// about unit prices raise a percentage they hand to a regulator.
//
// Render the count from len(HBOMManufacturingFields) — never write the number.
var HBOMManufacturingFields = []ProfileField{
	{ID: FieldAxebomHbomMfg01Designators, Ordinal: 0, Name: "Designators", CanonicalPath: "hardware_component.designators[]", CycloneDXPath: "", SPDXPath: "", Type: "string_list", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg02PackageFootprint, Ordinal: 0, Name: "Package / Footprint", CanonicalPath: "hardware_component.package_footprint", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg03Quantity, Ordinal: 0, Name: "Quantity", CanonicalPath: "hardware_component.quantity", CycloneDXPath: "", SPDXPath: "", Type: "number", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg04Description, Ordinal: 0, Name: "Description", CanonicalPath: "hardware_component.product_details", CycloneDXPath: "", SPDXPath: "", Type: "text", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg05SupplierSku, Ordinal: 0, Name: "Supplier SKU", CanonicalPath: "hardware_component.supplier_sku", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg06PreferredSupplier, Ordinal: 0, Name: "Preferred supplier", CanonicalPath: "hardware_component.preferred_supplier", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg07Alternates, Ordinal: 0, Name: "Alternate sources", CanonicalPath: "hardware_component.alternates[]", CycloneDXPath: "", SPDXPath: "", Type: "ref_list", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg08UnitPrice, Ordinal: 0, Name: "Unit price", CanonicalPath: "hardware_component.unit_price", CycloneDXPath: "", SPDXPath: "", Type: "number", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg09Currency, Ordinal: 0, Name: "Currency", CanonicalPath: "hardware_component.currency", CycloneDXPath: "", SPDXPath: "", Type: "string", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg10DoNotPopulate, Ordinal: 0, Name: "DNI / DNP", CanonicalPath: "hardware_component.do_not_populate", CycloneDXPath: "", SPDXPath: "", Type: "boolean", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg11AssemblyType, Ordinal: 0, Name: "Assembly type", CanonicalPath: "hardware_component.assembly_type", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 1, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
	{ID: FieldAxebomHbomMfg12LifecycleStatus, Ordinal: 0, Name: "Lifecycle status", CanonicalPath: "hardware_component.lifecycle_status", CycloneDXPath: "", SPDXPath: "", Type: "enum", Weight: 3, Required: false, Scored: true, SourcePage: 0, Status: "extension"},
}
