// Command notification is the EncoreBOM notification service.
//
// Email and webhook delivery.
//
// GENERATED by tools/gen-service. The scaffold — wiring, health, shutdown — is
// regenerated; handlers and business logic are hand-written under internal/.
// Re-running the generator will not clobber internal/.
package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"

	"github.com/encorebom/encorebom/libs/go-shared/platform/config"
	"github.com/encorebom/encorebom/libs/go-shared/platform/health"
	"github.com/encorebom/encorebom/libs/go-shared/platform/httpx"
	"github.com/encorebom/encorebom/libs/go-shared/platform/obs"
)

const serviceName = "notification"

// Injected at release time via -ldflags. See cmd/encorebom/version.go for why
// build provenance is load-bearing rather than cosmetic.
var version = "dev"

func main() {
	if err := run(); err != nil {
		// slog may not be configured yet if config loading is what failed.
		fmt.Fprintf(os.Stderr, "%s: %v\n", serviceName, err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.LoadService(serviceName)
	if err != nil {
		return err
	}

	obs.InitLogger(obs.LogConfig{
		Service: serviceName,
		Level:   cfg.LogLevel,
		Format:  cfg.LogFormat,
	})
	slog.Info("starting", "version", version, "config", cfg.String())

	ctx := context.Background()

	shutdownTracer, err := obs.InitTracer(ctx, obs.TraceConfig{
		Service:     serviceName,
		Namespace:   cfg.OTel.Namespace,
		Endpoint:    cfg.OTel.Endpoint,
		Env:         string(cfg.Env),
		SampleRatio: 0.1,
	})
	if err != nil {
		// Telemetry being unavailable must never prevent a service from
		// starting. Degrade loudly, serve traffic.
		slog.Warn("tracing disabled", "cause", err.Error())
		shutdownTracer = func(context.Context) error { return nil }
	}
	defer func() { _ = shutdownTracer(context.Background()) }()

	metrics := obs.NewMetrics(serviceName)

	// Dependencies are built ONCE, here, and handed to both hooks.
	//
	// The alternative — each hook opening its own pool, or a package-level
	// singleton — gives a service two connection pools and no single place
	// where startup can fail cleanly. buildDeps returns an error so a database
	// that is not reachable stops the process instead of producing an instance
	// that serves 500s and passes liveness.
	d, err := buildDeps(ctx, cfg)
	if err != nil {
		return fmt.Errorf("build dependencies: %w", err)
	}
	defer d.Close()

	checker := health.New(serviceName, version)
	registerHealthChecks(checker, d)

	mux := http.NewServeMux()
	checker.Mount(mux)
	registerRoutes(mux, d)

	// Catch-all. Without it, ServeMux answers unmatched routes with its own
	// text/plain "404 page not found", which breaks the error contract in
	// docs/02-CONTRACTS.md §9 and gives cross-tenant 404s a different shape
	// from routing 404s — an oracle for probing which ids exist.
	mux.HandleFunc("/", httpx.NotFound)

	// The shared chain first (request id, recovery, logging, security headers,
	// metrics), then anything this service adds. Order matters: a middleware
	// appended here runs INSIDE the shared ones, so a panic it causes is still
	// recovered and its requests are still logged with a request id.
	chain := append(httpx.Default(metrics, cfg.WriteTimeout), serviceMiddleware(d)...)
	handler := httpx.Chain(mux, chain...)

	// Background workers start BEFORE the server, so a queued backlog begins
	// draining at once rather than after the first request arrives.
	//
	// This hook lives in deps.go — a PRESERVED file — because a service that
	// needs a consumer or a scheduler must not hand-edit this generated one
	// (ADR-0001 mitigation 1). A service with no workers keeps the no-op.
	startBackground(ctx, d)

	return httpx.Run(ctx, httpx.ServerConfig{
		Addr:          fmt.Sprintf(":%d", cfg.HTTPPort),
		MetricsAddr:   fmt.Sprintf(":%d", cfg.MetricsPort),
		Handler:       handler,
		Metrics:       metrics,
		ReadTimeout:   cfg.ReadTimeout,
		WriteTimeout:  cfg.WriteTimeout,
		IdleTimeout:   cfg.IdleTimeout,
		ShutdownGrace: cfg.ShutdownGrace,
	})
}
