// Command gen-service scaffolds an EncoreBOM Go service.
//
// WHY THIS EXISTS (docs/ADR/0001, mitigation 1):
//
// The architecture is eight Go services, built by an agent with fresh context
// each session. Hand-writing the ninth service's boilerplate is where drift
// starts — one service ends up with a slightly different middleware order, or
// misses the metrics listener, and nothing catches it because each service
// compiles fine on its own.
//
// So: EVERY service is generated by this tool, including the first. If the
// generator cannot produce a service, that is a bug in the generator, not a
// reason to write the service by hand.
//
// Regeneration is safe. Scaffold files (main.go, Dockerfile) are overwritten;
// hand-edited files (routes.go, health.go, anything under internal/) are
// written only when absent.
//
// Usage:
//
//	go run ./tools/gen-service --name report
//	go run ./tools/gen-service --all
//	go run ./tools/gen-service --all --dry-run
package main

import (
	"bytes"
	"embed"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"text/template"
)

//go:embed templates/*.tmpl
var templates embed.FS

// serviceSpec describes one service. This table is the registry: adding a
// service means adding a row here and running the generator.
type serviceSpec struct {
	Name    string
	Summary string
	Port    int
	Phase   int
}

// MetricsPort is the service's own metrics listener.
//
// Derived, never listed in the registry above. A second hand-maintained column
// would drift from config.defaultMetricsPort, and the symptom is a container
// that EXPOSEs one port while the process binds another — which looks correct
// in the Dockerfile and fails only when something tries to scrape it.
func (s serviceSpec) MetricsPort() int { return s.Port + 10000 }

// GoVersion is the toolchain minor version, read from go.mod.
//
// It is NOT written in the Dockerfile template. The build image and the module
// must agree: a module declaring `go 1.26.2` cannot be built by golang:1.24,
// and the failure is `go.mod requires go >= 1.26.2` at `go mod download` —
// after the layer cache has already been invalidated, so it reads as a network
// or cache problem rather than a version mismatch. Reading go.mod means a
// toolchain bump regenerates the Dockerfiles, and CI's generator-diff job
// fails if someone forgets.
func (s serviceSpec) GoVersion() string {
	v, err := goVersion()
	if err != nil {
		// Reached only from a template, where returning an error is not an
		// option. Rendering an obviously-invalid tag beats rendering a
		// plausible wrong one: `FROM golang:UNKNOWN-alpine` fails the docker
		// build immediately and says why, whereas a silently stale default
		// would produce an image that builds and then cannot compile the
		// module.
		return "UNKNOWN"
	}
	return v
}

var goDirective = regexp.MustCompile(`(?m)^go\s+(\d+)\.(\d+)`)

// goVersion reads the toolchain minor version from go.mod.
//
// Resolved by walking UP from the working directory, not by reading "go.mod"
// relative to it. `go test` runs with the package directory as the working
// directory, so a bare relative read works under `go run ./tools/gen-service`
// from the repo root and fails under `go test ./tools/gen-service` — and doing
// it in an init() turned that into a panic at package import, taking down the
// whole test binary before a single test ran.
//
// Lazy, and returns an error rather than panicking: a code generator that
// cannot be imported is worse than one that reports a bad configuration.
func goVersion() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		// #nosec G304 -- dir starts at the working directory and only ever
		// walks toward the filesystem root; the filename is the constant
		// "go.mod". No caller-controlled input reaches this path.
		b, err := os.ReadFile(filepath.Join(dir, "go.mod"))
		if err == nil {
			m := goDirective.FindSubmatch(b)
			if m == nil {
				return "", fmt.Errorf("gen-service: no `go` directive in %s/go.mod", dir)
			}
			return fmt.Sprintf("%s.%s", m[1], m[2]), nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("gen-service: no go.mod found above %q", dir)
		}
		dir = parent
	}
}

var services = []serviceSpec{
	{"gateway", "API gateway: authentication, routing, rate limiting, WebSocket fan-out.", 8080, 3},
	{"auth", "Identity: GitHub SSO, local accounts, JWT, RBAC, invitations, audit.", 8091, 3},
	{"project", "Projects: owners, validity, classifications, practices, repository connections.", 8092, 4},
	{"scan-orchestrator", "Scan lifecycle: job fan-out, engine tracking, aggregation, progress.", 8093, 6},
	{"report", "Reports: SPDX/CycloneDX export, PDF/XLSX/JSON rendering, signing, sharing.", 8094, 9},
	{"campaign", "Campaigns: cron scheduling, recurring scan triggers, run history.", 8095, 14},
	{"comment", "Threaded comments on reports.", 8096, 13},
	{"notification", "Email and webhook delivery.", 8097, 14},
}

// generated files are always rewritten; preserved files are written once.
type fileSpec struct {
	tmpl     string
	dest     func(s serviceSpec) string
	preserve bool // true => never overwrite an existing file
	gofmt    bool
}

var files = []fileSpec{
	{tmpl: "main.go.tmpl", gofmt: true,
		dest: func(s serviceSpec) string { return filepath.Join("services", s.Name, "main.go") }},
	{tmpl: "routes.go.tmpl", gofmt: true, preserve: true,
		dest: func(s serviceSpec) string { return filepath.Join("services", s.Name, "routes.go") }},
	{tmpl: "health.go.tmpl", gofmt: true, preserve: true,
		dest: func(s serviceSpec) string { return filepath.Join("services", s.Name, "health.go") }},
	{tmpl: "deps.go.tmpl", gofmt: true, preserve: true,
		dest: func(s serviceSpec) string { return filepath.Join("services", s.Name, "deps.go") }},
	{tmpl: "Dockerfile.tmpl",
		dest: func(s serviceSpec) string { return filepath.Join("deploy", "docker", "Dockerfile."+s.Name) }},
}

func main() {
	var (
		name   = flag.String("name", "", "service to generate")
		all    = flag.Bool("all", false, "generate every registered service")
		dryRun = flag.Bool("dry-run", false, "report what would change without writing")
		list   = flag.Bool("list", false, "list registered services")
	)
	flag.Parse()

	if *list {
		for _, s := range services {
			fmt.Printf("%-18s port %d  phase %-2d  %s\n", s.Name, s.Port, s.Phase, s.Summary)
		}
		return
	}

	var targets []serviceSpec
	switch {
	case *all:
		targets = services
	case *name != "":
		found := false
		for _, s := range services {
			if s.Name == *name {
				targets = []serviceSpec{s}
				found = true
				break
			}
		}
		if !found {
			// Refusing an unregistered name is deliberate: the registry above is
			// the source of truth for what services exist, and a typo should not
			// silently create a ninth service nobody knows about.
			fmt.Fprintf(os.Stderr, "unknown service %q\n\nregistered:\n", *name)
			for _, s := range services {
				fmt.Fprintf(os.Stderr, "  %s\n", s.Name)
			}
			fmt.Fprintf(os.Stderr, "\nTo add a service, add it to `services` in tools/gen-service/main.go.\n")
			os.Exit(1)
		}
	default:
		flag.Usage()
		os.Exit(2)
	}

	root, err := repoRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var created, updated, skipped int
	for _, s := range targets {
		for _, f := range files {
			dest := filepath.Join(root, f.dest(s))
			action, err := render(dest, f, s, *dryRun)
			if err != nil {
				fmt.Fprintf(os.Stderr, "%s: %v\n", f.dest(s), err)
				os.Exit(1)
			}
			switch action {
			case "create":
				created++
			case "update":
				updated++
			case "skip":
				skipped++
			}
			if action != "skip" || *dryRun {
				fmt.Printf("  %-7s %s\n", action, f.dest(s))
			}
		}
	}

	verb := "wrote"
	if *dryRun {
		verb = "would write"
	}
	fmt.Printf("\n%s %d new, %d regenerated, %d preserved (%d service(s))\n",
		verb, created, updated, skipped, len(targets))
	if skipped > 0 && !*dryRun {
		fmt.Println("preserved files are hand-edited and are never overwritten")
	}
}

func render(dest string, f fileSpec, s serviceSpec, dryRun bool) (string, error) {
	_, statErr := os.Stat(dest)
	exists := statErr == nil

	if exists && f.preserve {
		return "skip", nil
	}

	tmpl, err := template.ParseFS(templates, "templates/"+f.tmpl)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, s); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	out := buf.Bytes()
	if f.gofmt {
		formatted, err := format.Source(out)
		if err != nil {
			// A template that produces unparseable Go is a generator bug, and
			// writing it would leave the tree uncompilable.
			return "", fmt.Errorf("generated Go does not parse: %w", err)
		}
		out = formatted
	}

	action := "create"
	if exists {
		// Skip the write when content is identical, so a no-op regeneration
		// does not churn file mtimes and confuse build caches.
		// #nosec G304 -- dest is built from this file's own service registry,
		// not from user input.
		if current, err := os.ReadFile(dest); err == nil && bytes.Equal(current, out) {
			return "skip", nil
		}
		action = "update"
	}

	if dryRun {
		return action, nil
	}
	// #nosec G301 -- generated source directories are world-readable by design.
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return "", err
	}
	// #nosec G306 -- generated Go source is meant to be world-readable.
	if err := os.WriteFile(dest, out, 0o644); err != nil {
		return "", err
	}
	return action, nil
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found walking up from the working directory")
		}
		dir = parent
	}
}

// serviceNames returns the registered service names, sorted.
//
// config.KnownServices() holds the runtime-facing copy; a drift test in Phase 1
// asserts the two lists agree, so a service added here but not there cannot
// silently get a default port.
func serviceNames() []string {
	out := make([]string, 0, len(services))
	for _, s := range services {
		out = append(out, s.Name)
	}
	sort.Strings(out)
	return out
}
