package store

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/axebom/axebom/services/report/internal/render"
)

// TestTheCoverageBreakdownDecodesTheREALSerializerOutput.
//
// ⚠ THE FIXTURE IS GENERATED BY THE ACTUAL PYTHON SERIALIZER, NOT HAND-WRITTEN,
// AND THAT IS THE ENTIRE POINT OF THIS TEST.
//
// Before it, this function decoded `fields` into a `map[string]…` while
// `CoverageResult.as_dict()` emits a LIST. `json.Unmarshal` returned an
// UnmarshalTypeError, the deliberate `//nolint:nilerr` swallowed it, and the
// per-field coverage table was EMPTY in every report this product had ever
// rendered — along with the formula string, which had decoded fine and was
// discarded with it. No error, no log line, no failing test: the section an
// auditor reads was simply blank.
//
// A hand-written fixture would not have caught it, because the hand would have
// written whatever shape the Go struct expected. Regenerate with:
//
//	.venv/bin/python -c "..."  > services/report/testdata/coverage_breakdown.json
func TestTheCoverageBreakdownDecodesTheREALSerializerOutput(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "testdata", "coverage_breakdown.json"))
	if err != nil {
		t.Fatalf("fixture: %v", err)
	}

	var out render.BOM
	if err := applyCoverageBreakdown(raw, &out); err != nil {
		t.Fatalf("applyCoverageBreakdown: %v", err)
	}

	if out.Coverage.Formula == "" {
		t.Error("the formula is empty — it is published so the number is auditable, " +
			"and it decoded correctly even while the fields did not")
	}
	if len(out.Coverage.Fields) != 2 {
		t.Fatalf("fields = %d, want 2 — an empty table here is the bug this test exists for",
			len(out.Coverage.Fields))
	}

	byID := map[string]render.FieldCoverage{}
	for _, f := range out.Coverage.Fields {
		byID[f.FieldID] = f
	}

	name, ok := byID["certin.sbom.01.component_name"]
	if !ok {
		t.Fatalf("component_name is missing; got %+v", out.Coverage.Fields)
	}
	if name.Present != 2 || name.Declared != 2 || name.Total != 2 {
		t.Errorf("component_name = %+v, want present/declared/total all 2", name)
	}

	// ⚠ THE ROW THAT PROVES THE TWO NUMBERS ARE DIFFERENT. One component has a
	// real licence and one has `not-provided`: declared 2, present 1. A decoder
	// that collapsed them would make invariant 3 unenforceable at the table.
	license := byID["certin.sbom.05.component_license"]
	if license.Present != 1 || license.Declared != 2 {
		t.Errorf("component_license = %+v, want present 1 declared 2 — `not-provided` "+
			"is declared but never counts as covered", license)
	}
}

// TestAMalformedBreakdownStillRendersTheHeadlineNumbers — the tolerant error
// handling is deliberate and stays. It is also what let the bug above hide for
// this long, which is why the SHAPE has to be right rather than the handling
// strict.
func TestAMalformedBreakdownStillRendersTheHeadlineNumbers(t *testing.T) {
	var out render.BOM
	if err := applyCoverageBreakdown([]byte(`{"fields": "not a list at all"}`), &out); err != nil {
		t.Errorf("a malformed breakdown must not fail the whole report: %v", err)
	}
	if len(out.Coverage.Fields) != 0 {
		t.Error("a malformed breakdown must yield no fields rather than partial ones")
	}
}
