"""Generated by 'axebom profile gen'. DO NOT EDIT.

Source: docs/reference/CERT-In_BOM_Guidelines_v2.0.pdf (profile certin-v2.0 revision 1)
Regenerate: task profile:gen

Editing this file is pointless — it is overwritten — and dangerous: the
coverage checker reads the PROFILE at runtime, so a hand-edit here would drift
from what actually scores a report.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ProfileField:
    id: str
    ordinal: int
    name: str
    canonical_path: str
    cyclonedx_path: str
    spdx_path: str
    type: str
    weight: int
    required: bool
    scored: bool
    source_page: int
    status: str
    #: The closed set an enum field accepts, empty for every other type.
    #:
    #: A trailing default so every positional construction above keeps working.
    values: tuple[str, ...] = ()


PROFILE_ID = "certin-v2.0"
PROFILE_REVISION = 1
PROFILE_ALL_VERIFIED = True

# Render counts from len(SBOM_FIELDS) — never write the number.
SBOM_FIELDS: list[ProfileField] = [
    ProfileField("certin.sbom.01.component_name", 1, "Component Name", "component.name", "components[].name", "packages[].name", "string", 3, True, True, 22, "verified"),
    ProfileField("certin.sbom.02.component_version", 2, "Component Version", "component.version_raw", "components[].version", "packages[].versionInfo", "string", 3, True, True, 22, "verified"),
    ProfileField("certin.sbom.03.component_description", 3, "Component Description", "component.description", "components[].description", "packages[].description", "text", 1, True, True, 23, "verified"),
    ProfileField("certin.sbom.04.component_supplier", 4, "Component Supplier", "component.supplier", "components[].supplier.name", "packages[].supplier", "string", 3, True, True, 23, "verified"),
    ProfileField("certin.sbom.05.component_license", 5, "Component License", "component.license_effective", "components[].licenses", "packages[].licenseConcluded", "spdx_expression", 3, True, True, 23, "verified"),
    ProfileField("certin.sbom.06.component_origin", 6, "Component Origin", "component.origin", "components[].properties[axebom:origin]", "packages[].originator", "enum", 3, True, True, 23, "verified", ("proprietary", "open-source", "third-party-vendor", "unknown", )),
    ProfileField("certin.sbom.07.component_dependencies", 7, "Component Dependencies", "component.dependencies[]", "dependencies[]", "relationships[DEPENDS_ON]", "ref_list", 3, True, True, 23, "verified"),
    ProfileField("certin.sbom.08.vulnerabilities", 8, "Vulnerabilities", "component.findings[]", "vulnerabilities[]", "relationships[HAS_ASSOCIATED_VULNERABILITY]", "ref_list", 3, True, True, 23, "verified"),
    ProfileField("certin.sbom.09.patch_status", 9, "Patch Status", "component.patch_status", "components[].properties[axebom:patch_status]", "annotations[]", "enum", 3, True, True, 23, "verified", ("up-to-date", "patch-available", "no-fix-available", "unknown", )),
    ProfileField("certin.sbom.10.release_date", 10, "Release Date", "component.release_date", "components[].properties[axebom:release_date]", "packages[].releaseDate", "date", 1, True, True, 23, "verified"),
    ProfileField("certin.sbom.11.eol_date", 11, "End-of-Life (EOL) Date", "component.eol_date", "components[].properties[axebom:eol_date]", "packages[].validUntilDate", "date", 1, True, True, 23, "verified"),
    ProfileField("certin.sbom.12.criticality", 12, "Criticality", "component.criticality", "components[].properties[axebom:criticality]", "annotations[]", "enum", 3, True, True, 23, "verified", ("critical", "high", "medium", "low", )),
    ProfileField("certin.sbom.13.usage_restrictions", 13, "Usage Restrictions", "component.usage_restrictions", "components[].properties[axebom:usage_restrictions]", "packages[].comment", "text", 1, True, True, 23, "verified"),
    ProfileField("certin.sbom.14.checksums", 14, "Checksums or Hashes", "component.hashes[]", "components[].hashes[]", "packages[].checksums[]", "hash_list", 3, True, True, 23, "verified"),
    ProfileField("certin.sbom.15.comments", 15, "Comments or Notes", "component.comments", "components[].properties[axebom:comments]", "packages[].comment", "text", 1, True, True, 23, "verified"),
    ProfileField("certin.sbom.16.author_of_sbom_data", 16, "Author of SBOM Data", "component.provenance[].author", "metadata.authors[]", "creationInfo.creators[]", "string", 3, True, True, 23, "verified"),
    ProfileField("certin.sbom.17.timestamp", 17, "Timestamp", "bom_document.generated_at", "metadata.timestamp", "creationInfo.created", "datetime", 3, True, True, 23, "verified"),
    ProfileField("certin.sbom.18.executable_property", 18, "Executable Property", "component.executable_property", "components[].properties[axebom:executable]", "packages[].primaryPackagePurpose", "tristate", 1, True, True, 24, "verified"),
    ProfileField("certin.sbom.19.archive_property", 19, "Archive Property", "component.archive_property", "components[].properties[axebom:archive]", "packages[].packageFileName", "tristate", 1, True, True, 24, "verified"),
    ProfileField("certin.sbom.20.structured_property", 20, "Structured Property", "component.structured_property", "components[].properties[axebom:structured]", "annotations[]", "tristate", 1, True, True, 24, "verified"),
    ProfileField("certin.sbom.21.unique_identifier", 21, "Unique Identifier", "component.certin_identifier", "components[].properties[axebom:certin_id]", "packages[].externalRefs[PACKAGE-MANAGER/purl]", "string", 3, True, True, 24, "verified"),
]

# Render counts from len(QBOM_FIELDS) — never write the number.
QBOM_FIELDS: list[ProfileField] = [
    ProfileField("certin.qbom.01.model_name", 0, "Model Name", "quantum_component.model_name", "", "", "string", 3, False, True, 44, "verified"),
    ProfileField("certin.qbom.02.version", 0, "Version", "quantum_component.version", "", "", "string", 3, False, True, 44, "verified"),
    ProfileField("certin.qbom.03.vendor_origin", 0, "Vendor & Origin Information", "quantum_component.vendor_origin", "", "", "string", 3, False, True, 44, "verified"),
    ProfileField("certin.qbom.04.license_information", 0, "License Information", "quantum_component.license_info", "", "", "string", 3, False, True, 44, "verified"),
    ProfileField("certin.qbom.05.cryptographic_asset", 0, "Cryptographic Asset", "quantum_component.crypto_assets[]", "", "", "ref_list", 3, False, True, 44, "verified"),
    ProfileField("certin.qbom.06.communication_protocol", 0, "Communication Protocol", "quantum_component.communication_protocol", "", "", "string", 3, False, True, 45, "verified"),
    ProfileField("certin.qbom.07.hardware", 0, "Hardware", "quantum_component.hardware", "", "", "text", 3, False, True, 45, "verified"),
    ProfileField("certin.qbom.08.software_dependencies", 0, "Software Dependencies", "quantum_component.software_dependencies", "", "", "ref_list", 3, False, True, 45, "verified"),
    ProfileField("certin.qbom.09.environmental_impact", 0, "Environmental Impact", "quantum_component.environmental_impact", "", "", "text", 1, False, True, 45, "verified"),
    ProfileField("certin.qbom.10.vulnerabilities", 0, "Vulnerabilities", "quantum_component.findings[]", "", "", "ref_list", 3, False, True, 45, "verified"),
    ProfileField("certin.qbom.11.attestations", 0, "Attestations", "quantum_component.attestation_signature", "", "", "signature", 3, False, True, 45, "verified"),
]

# Render counts from len(AIBOM_FIELDS) — never write the number.
AIBOM_FIELDS: list[ProfileField] = [
    ProfileField("certin.aibom.01.model_name", 0, "Model Name", "ai_model.model_name", "", "", "string", 3, False, True, 54, "verified"),
    ProfileField("certin.aibom.02.model_version", 0, "Model Version", "ai_model.model_version", "", "", "string", 3, False, True, 54, "verified"),
    ProfileField("certin.aibom.03.model_type", 0, "Model Type", "ai_model.model_type", "", "", "string", 3, False, True, 54, "verified"),
    ProfileField("certin.aibom.04.model_developer", 0, "Model Developer", "ai_model.model_developer", "", "", "string", 3, False, True, 54, "verified"),
    ProfileField("certin.aibom.05.licensing", 0, "Model Licensing Information", "ai_model.licensing", "", "", "spdx_expression", 3, False, True, 54, "verified"),
    ProfileField("certin.aibom.06.software_dependencies", 0, "Software Dependencies", "ai_model.software_dependencies[]", "", "", "ref_list", 3, False, True, 54, "verified"),
    ProfileField("certin.aibom.07.ml_models_algorithms", 0, "ML Models and Algorithms", "ai_model.ml_models_algorithms[]", "", "", "string_list", 3, False, True, 54, "verified"),
    ProfileField("certin.aibom.08.performance_metrics", 0, "Model Performance Metrics", "ai_model.performance_metrics", "", "", "json", 1, False, True, 54, "verified"),
    ProfileField("certin.aibom.09.data_source", 0, "Data Source", "ai_model.data_source", "", "", "text", 3, False, True, 54, "verified"),
    ProfileField("certin.aibom.10.data_sets", 0, "Data Sets", "ai_model.data_sets[]", "", "", "ref_list", 3, False, True, 55, "verified"),
    ProfileField("certin.aibom.11.hardware", 0, "Hardware", "ai_model.hardware", "", "", "text", 1, False, True, 55, "verified"),
    ProfileField("certin.aibom.12.security_requirements", 0, "Security Requirements", "ai_model.security_requirements", "", "", "text", 3, False, True, 55, "verified"),
    ProfileField("certin.aibom.13.input", 0, "Input", "ai_model.input", "", "", "string", 3, False, True, 55, "verified"),
    ProfileField("certin.aibom.14.output", 0, "Output", "ai_model.output", "", "", "string", 3, False, True, 55, "verified"),
    ProfileField("certin.aibom.15.intended_usage", 0, "Intended Usage", "ai_model.intended_usage", "", "", "text", 3, False, True, 55, "verified"),
    ProfileField("certin.aibom.16.out_of_scope_usage", 0, "Out of Scope Usage", "ai_model.out_of_scope_usage", "", "", "text", 3, False, True, 55, "verified"),
    ProfileField("certin.aibom.17.environmental_impact", 0, "Environmental Impact", "ai_model.environmental_impact", "", "", "text", 1, False, True, 55, "verified"),
    ProfileField("certin.aibom.18.vulnerabilities", 0, "Vulnerabilities", "ai_model.findings[]", "", "", "ref_list", 3, False, True, 55, "verified"),
    ProfileField("certin.aibom.19.attestations", 0, "Attestations", "ai_model.attestation_signature", "", "", "signature", 3, False, True, 55, "verified"),
]

# Render counts from len(HBOM_FIELDS) — never write the number.
HBOM_FIELDS: list[ProfileField] = [
    ProfileField("certin.hbom.01.product_name", 0, "Product Name", "hardware_component.product_name", "", "", "string", 3, False, True, 60, "verified"),
    ProfileField("certin.hbom.02.product_version", 0, "Product Version", "hardware_component.product_version", "", "", "string", 3, False, True, 60, "verified"),
    ProfileField("certin.hbom.03.product_details", 0, "Product Details", "hardware_component.product_details", "", "", "text", 1, False, True, 60, "verified"),
    ProfileField("certin.hbom.04.warranty_amc", 0, "Warranty/AMC", "hardware_component.warranty_amc", "", "", "text", 1, False, True, 60, "verified"),
    ProfileField("certin.hbom.05.manufacturer_name", 0, "Manufacturer Name", "hardware_component.manufacturer_name", "", "", "string", 3, False, True, 60, "verified"),
    ProfileField("certin.hbom.06.manufacturer_location", 0, "Manufacturer Location", "hardware_component.manufacturer_location", "", "", "string", 3, False, True, 60, "verified"),
    ProfileField("certin.hbom.07.manufacturing_date", 0, "Manufacturing Date", "hardware_component.manufacturing_date", "", "", "date", 1, False, True, 60, "verified"),
    ProfileField("certin.hbom.08.supplier_information", 0, "Supplier Information", "hardware_component.supplier_info", "", "", "text", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.09.supplier_location", 0, "Supplier Location", "hardware_component.supplier_location", "", "", "string", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.10.model_number", 0, "Model Number", "hardware_component.model_number", "", "", "string", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.11.serial_number", 0, "Serial Number", "hardware_component.serial_number", "", "", "string", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.12.technical_specification", 0, "Technical Specification", "hardware_component.technical_specification", "", "", "text", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.13.component_supplier_information", 0, "Supplier Information (component)", "hardware_component.component_supplier_info", "", "", "text", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.14.component_supplier_location", 0, "Supplier Location (component)", "hardware_component.component_supplier_location", "", "", "string", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.15.technology_node", 0, "Technology Node", "hardware_component.technology_node", "", "", "string", 1, False, True, 61, "verified"),
    ProfileField("certin.hbom.16.compliance", 0, "Compliance", "hardware_component.compliance[]", "", "", "string_list", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.17.power_supply", 0, "Power supply", "hardware_component.power_supply", "", "", "text", 1, False, True, 61, "verified"),
    ProfileField("certin.hbom.18.license_information", 0, "License Information", "hardware_component.license_info", "", "", "text", 1, False, True, 61, "verified"),
    ProfileField("certin.hbom.19.test_result", 0, "Test Result", "hardware_component.test_result", "", "", "text", 1, False, True, 61, "verified"),
    ProfileField("certin.hbom.20.sub_component", 0, "Sub-component", "hardware_component.children[]", "", "", "recursive_ref", 3, False, True, 61, "verified"),
    ProfileField("certin.hbom.21.firmware_version", 0, "Firmware Version", "hardware_component.firmware_version", "", "", "string", 3, False, True, 62, "verified"),
    ProfileField("certin.hbom.22.origin", 0, "Origin", "hardware_component.origin", "", "", "string", 3, False, True, 62, "verified"),
    ProfileField("certin.hbom.23.criticality", 0, "Criticality Rating", "hardware_component.criticality", "", "", "enum", 3, False, True, 62, "verified", ("critical", "high", "medium", "low", )),
    ProfileField("certin.hbom.24.vulnerabilities", 0, "Vulnerabilities", "hardware_component.findings[]", "", "", "ref_list", 3, False, True, 62, "verified"),
]

# TYPE-DISCRIMINATED (CERT-In Table 9). Score each crypto asset against the
# field set for ITS asset_type — see the Go comment for why this matters.
CRYPTO_FIELDS_BY_ASSET_TYPE: dict[str, list[ProfileField]] = {
    "algorithm": [
        ProfileField("certin.crypto.algo.name", 0, "Name", "crypto_asset.name", "", "", "string", 3, False, True, 45, "verified"),
        ProfileField("certin.crypto.algo.asset_type", 0, "Asset Type", "crypto_asset.asset_type", "", "", "enum", 3, False, True, 45, "verified", ("algorithm", )),
        ProfileField("certin.crypto.algo.primitive", 0, "Primitive", "crypto_asset.primitive", "", "", "string", 3, False, True, 45, "verified"),
        ProfileField("certin.crypto.algo.mode", 0, "Mode", "crypto_asset.mode", "", "", "string", 3, False, True, 45, "verified"),
        ProfileField("certin.crypto.algo.crypto_functions", 0, "Crypto Functions", "crypto_asset.crypto_functions[]", "", "", "string_list", 3, False, True, 46, "verified"),
        ProfileField("certin.crypto.algo.security_level", 0, "Classical security level", "crypto_asset.classical_security_level", "", "", "integer", 3, False, True, 46, "verified"),
        ProfileField("certin.crypto.algo.oid", 0, "OID", "crypto_asset.oid", "", "", "string", 3, False, True, 46, "verified"),
        ProfileField("certin.crypto.algo.list", 0, "List", "crypto_asset.algorithm_list[]", "", "", "string_list", 1, False, True, 46, "verified"),
    ],
    "certificate": [
        ProfileField("certin.crypto.cert.name", 0, "Name", "crypto_asset.name", "", "", "string", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.cert.asset_type", 0, "Asset Type", "crypto_asset.asset_type", "", "", "enum", 3, False, True, 47, "verified", ("certificate", )),
        ProfileField("certin.crypto.cert.subject_name", 0, "Subject Name", "crypto_asset.cert_subject", "", "", "string", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.cert.issuer_name", 0, "Issuer Name", "crypto_asset.cert_issuer", "", "", "string", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.cert.not_valid_before", 0, "Not Valid Before", "crypto_asset.not_valid_before", "", "", "datetime", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.cert.not_valid_after", 0, "Not Valid After", "crypto_asset.not_valid_after", "", "", "datetime", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.cert.sig_algo_ref", 0, "Signature Algorithm Reference", "crypto_asset.signature_algo_ref", "", "", "string", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.cert.subject_pk_ref", 0, "Subject Public Key Reference", "crypto_asset.subject_public_key_ref", "", "", "string", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.cert.format", 0, "Certificate Format", "crypto_asset.cert_format", "", "", "string", 1, False, True, 47, "verified"),
        ProfileField("certin.crypto.cert.extension", 0, "Certificate Extension", "crypto_asset.cert_extension", "", "", "string", 1, False, True, 48, "verified"),
    ],
    "key": [
        ProfileField("certin.crypto.key.name", 0, "Name", "crypto_asset.name", "", "", "string", 3, False, True, 46, "verified"),
        ProfileField("certin.crypto.key.asset_type", 0, "Asset Type", "crypto_asset.asset_type", "", "", "enum", 3, False, True, 46, "verified", ("key", )),
        ProfileField("certin.crypto.key.id", 0, "id", "crypto_asset.key_id", "", "", "string", 3, False, True, 46, "verified"),
        ProfileField("certin.crypto.key.state", 0, "state", "crypto_asset.key_state", "", "", "enum", 3, False, True, 46, "verified", ("active", "revoked", "expired", "unknown", )),
        ProfileField("certin.crypto.key.size", 0, "size", "crypto_asset.key_size", "", "", "integer", 3, False, True, 46, "verified"),
        ProfileField("certin.crypto.key.creation_date", 0, "Creation Date", "crypto_asset.creation_date", "", "", "date", 1, False, True, 46, "verified"),
        ProfileField("certin.crypto.key.activation_date", 0, "Activation Date", "crypto_asset.activation_date", "", "", "date", 1, False, True, 46, "verified"),
    ],
    "protocol": [
        ProfileField("certin.crypto.proto.name", 0, "Name", "crypto_asset.name", "", "", "string", 3, False, True, 46, "verified"),
        ProfileField("certin.crypto.proto.asset_type", 0, "Asset Type", "crypto_asset.asset_type", "", "", "enum", 3, False, True, 47, "verified", ("protocol", )),
        ProfileField("certin.crypto.proto.version", 0, "Version", "crypto_asset.protocol_version", "", "", "string", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.proto.cipher_suites", 0, "Cipher Suites", "crypto_asset.cipher_suites[]", "", "", "string_list", 3, False, True, 47, "verified"),
        ProfileField("certin.crypto.proto.oid", 0, "OID", "crypto_asset.oid", "", "", "string", 1, False, True, 47, "verified"),
    ],
}

# CERT-In Table 5 category 3 — per-PROJECT settings, not a report section.
PRACTICE_FIELDS: list[ProfileField] = [
    ProfileField("certin.sbom.pp.frequency", 0, "Frequency", "", "", "", "string", 3, False, True, 0, "verified"),
    ProfileField("certin.sbom.pp.depth", 0, "Depth", "", "", "", "enum", 3, False, True, 0, "verified"),
    ProfileField("certin.sbom.pp.known_unknowns", 0, "Known Unknowns", "", "", "", "text", 3, False, True, 0, "verified"),
    ProfileField("certin.sbom.pp.distribution_and_delivery", 0, "Distribution and Delivery", "", "", "", "text", 3, False, True, 0, "verified"),
    ProfileField("certin.sbom.pp.access_control", 0, "Access Control", "", "", "", "enum", 3, False, True, 0, "verified", ("public", "private", )),
    ProfileField("certin.sbom.pp.accommodation_of_mistakes", 0, "Accommodation of Mistakes", "", "", "", "text", 3, False, True, 0, "verified"),
]

BOM_LEVELS: list[str] = [
    "top_level",
    "n_level",
    "delivery",
    "transitive",
    "complete",
]

SDLC_CLASSIFICATIONS: list[str] = [
    "design",
    "source",
    "build",
    "analyzed",
    "deployed",
    "runtime",
]

VEX_STATUSES: list[str] = [
    "not_affected",
    "affected",
    "fixed",
    "under_investigation",
]

