package compliance

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Code generation from the profile.
//
// Go structs and Python models are GENERATED so the field list exists once
// (ADR-0007). The generated files carry a do-not-edit banner and are listed in
// .gitignore: a hand-edit would be silently overwritten, and worse, would drift
// from the profile the coverage checker reads at runtime.
//
// Output is byte-stable — every map is sorted before emission — so a
// regeneration that changes nothing produces no diff. Unstable codegen is how a
// real change gets lost in noise.

const doNotEdit = "// Code generated by `axebom profile gen`. DO NOT EDIT.\n" +
	"//\n" +
	"// Source: %s (profile %s revision %d)\n" +
	"// Regenerate: task profile:gen\n" +
	"//\n" +
	"// Editing this file is pointless — it is overwritten — and dangerous: the\n" +
	"// coverage checker reads the PROFILE at runtime, so a hand-edit here would\n" +
	"// drift from what actually scores a report.\n\n"

// GenerateGo writes the Go model.
func GenerateGo(p *Profile, outDir string) (string, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, doNotEdit, p.Meta.SourceDocument, p.Meta.ID, p.Meta.Revision)
	b.WriteString("package model\n\n")

	b.WriteString(`// ProfileField mirrors one entry in the compliance profile.
type ProfileField struct {
	ID            string
	Ordinal       int
	Name          string
	CanonicalPath string
	CycloneDXPath string
	SPDXPath      string
	Type          string
	Weight        int
	Required      bool
	Scored        bool
	SourcePage    int
	Status        string
}

`)

	fmt.Fprintf(&b, "// ProfileID identifies the standard these fields come from.\n")
	fmt.Fprintf(&b, "const ProfileID = %q\n\n", p.Meta.ID)
	fmt.Fprintf(&b, "// ProfileRevision is bumped whenever the profile changes.\n")
	fmt.Fprintf(&b, "const ProfileRevision = %d\n\n", p.Meta.Revision)
	fmt.Fprintf(&b, "// ProfileAllVerified reports whether every entry was transcribed from the\n")
	fmt.Fprintf(&b, "// source document. When false, reports must say so.\n")
	fmt.Fprintf(&b, "const ProfileAllVerified = %v\n\n", p.Meta.AllEntriesVerified)

	// --- field id constants --------------------------------------------------
	b.WriteString("// Field identifiers. Stable forever — referenced by tests,\n")
	b.WriteString("// diagnostics and report anchors. Never renumber.\nconst (\n")
	for _, f := range p.AllFields() {
		fmt.Fprintf(&b, "\t%s = %q\n", goConstName(f.ID), f.ID)
	}
	b.WriteString(")\n\n")

	// --- per-BOM-type field sets ---------------------------------------------
	for _, bomType := range []string{"SBOM", "QBOM", "AIBOM", "HBOM"} {
		fields := p.FieldsForBOMType(bomType)
		if len(fields) == 0 {
			continue
		}
		fmt.Fprintf(&b, "// %sFields are the scored required elements for a %s.\n//\n", bomType, bomType)
		fmt.Fprintf(&b, "// Render the count from len(%sFields) — never write the number.\n", bomType)
		fmt.Fprintf(&b, "var %sFields = []ProfileField{\n", bomType)
		for _, f := range fields {
			writeGoField(&b, f)
		}
		b.WriteString("}\n\n")
	}

	// --- crypto: TYPE-DISCRIMINATED ------------------------------------------
	b.WriteString(`// CryptoFieldsByAssetType is TYPE-DISCRIMINATED (CERT-In Table 9).
//
// The four asset types have DIFFERENT field sets. Coverage must be scored
// against the set for the row's asset_type: scoring a certificate against
// key_size would report every CBOM at roughly 30% coverage — falsely, in a
// document shown to a regulator.
var CryptoFieldsByAssetType = map[string][]ProfileField{
`)
	for _, name := range p.cryptoTypeNames() {
		t := p.CryptoAsset.Types[name]
		fmt.Fprintf(&b, "\t%q: {\n", t.AssetTypeValue)
		for _, f := range t.Fields {
			if f.IsScored() {
				b.WriteString("\t")
				writeGoField(&b, f)
			}
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	// --- practices -----------------------------------------------------------
	for _, c := range p.SBOM.MinimumElementCategories {
		if c.Kind != "per_project_settings" {
			continue
		}
		b.WriteString("// PracticeFields are CERT-In Table 5 category 3 — per-PROJECT settings,\n")
		b.WriteString("// not a report section. Implementing only the data fields and claiming\n")
		b.WriteString("// CERT-In compliance is overstating.\n")
		b.WriteString("var PracticeFields = []ProfileField{\n")
		for _, f := range c.SubElements {
			writeGoField(&b, f)
		}
		b.WriteString("}\n\n")
	}

	// --- VEX / CSAF ------------------------------------------------------------
	if len(p.VEX.AdditionalFields) > 0 {
		b.WriteString("// VEXFields are CERT-In §6's per-statement fields (p.35) — scored over\n")
		b.WriteString("// findings that have an effective VEX statement, not over every finding.\n")
		b.WriteString("var VEXFields = []ProfileField{\n")
		for _, f := range p.VEX.AdditionalFields {
			writeGoField(&b, f)
		}
		b.WriteString("}\n\n")
	}
	if len(p.CSAF.RequiredContent) > 0 {
		b.WriteString("// CSAFFields are CERT-In §6's per-advisory required content (p.35) —\n")
		b.WriteString("// scored over findings whose winning VEX statement has a generated CSAF\n")
		b.WriteString("// advisory.\n")
		b.WriteString("var CSAFFields = []ProfileField{\n")
		for _, f := range p.CSAF.RequiredContent {
			writeGoField(&b, f)
		}
		b.WriteString("}\n\n")
	}

	// --- enums ---------------------------------------------------------------
	writeGoStringSlice(&b, "BOMLevels", "BOM depth levels (CERT-In §3.1).", levelIDs(p.SBOM.Levels))
	writeGoStringSlice(&b, "SDLCClassifications", "SDLC stages (CERT-In §3.2).", levelIDs(p.SBOM.Classifications))
	writeGoStringSlice(&b, "VEXStatuses", "The four VEX statuses (CERT-In §6).", vexIDs(p.VEX.Statuses))

	src, err := format.Source(b.Bytes())
	if err != nil {
		return "", fmt.Errorf("generated Go does not parse: %w", err)
	}

	path := filepath.Join(outDir, "generated_certin.go")
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, src, 0o600); err != nil {
		return "", err
	}
	return path, nil
}

func writeGoField(b *bytes.Buffer, f Field) {
	fmt.Fprintf(b, "\t{ID: %s, Ordinal: %d, Name: %q, CanonicalPath: %q, "+
		"CycloneDXPath: %q, SPDXPath: %q, Type: %q, Weight: %d, Required: %v, "+
		"Scored: %v, SourcePage: %d, Status: %q},\n",
		goConstName(f.ID), f.Ordinal, f.Name, f.CanonicalPath,
		f.CycloneDXPath, f.SPDXPath, f.Type, f.Weight, f.Required,
		f.IsScored(), f.SourcePage, f.Status)
}

func writeGoStringSlice(b *bytes.Buffer, name, doc string, values []string) {
	fmt.Fprintf(b, "// %s are %s\nvar %s = []string{\n", name, doc, name)
	for _, v := range values {
		fmt.Fprintf(b, "\t%q,\n", v)
	}
	b.WriteString("}\n\n")
}

// goConstName turns certin.sbom.01.component_name into
// FieldCertinSbom01ComponentName.
func goConstName(id string) string {
	parts := strings.FieldsFunc(id, func(r rune) bool { return r == '.' || r == '_' })
	var sb strings.Builder
	sb.WriteString("Field")
	for _, p := range parts {
		if p == "" {
			continue
		}
		sb.WriteString(strings.ToUpper(p[:1]))
		sb.WriteString(p[1:])
	}
	return sb.String()
}

func levelIDs(ls []Level) []string {
	out := make([]string, 0, len(ls))
	for _, l := range ls {
		out = append(out, l.ID)
	}
	return out
}

func vexIDs(ss []VEXStat) []string {
	out := make([]string, 0, len(ss))
	for _, s := range ss {
		out = append(out, s.ID)
	}
	return out
}

// GeneratePython writes the Python model.
//
// Deliberately data-only: the Go and Python sides must agree on names, counts
// and weights, and the surest way to guarantee that is for both to be
// projections of the same YAML rather than two hand-maintained lists. A test
// asserts they agree.
func GeneratePython(p *Profile, outDir string) (string, error) {
	var b bytes.Buffer

	// NOTE: this is a Go raw string literal, so it must contain no backticks.
	// An earlier version wrote the command name in double-backticks (RST
	// literal syntax) and silently terminated the literal here.
	fmt.Fprintf(&b, `"""Generated by 'axebom profile gen'. DO NOT EDIT.

Source: %s (profile %s revision %d)
Regenerate: task profile:gen

Editing this file is pointless — it is overwritten — and dangerous: the
coverage checker reads the PROFILE at runtime, so a hand-edit here would drift
from what actually scores a report.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ProfileField:
    id: str
    ordinal: int
    name: str
    canonical_path: str
    cyclonedx_path: str
    spdx_path: str
    type: str
    weight: int
    required: bool
    scored: bool
    source_page: int
    status: str


PROFILE_ID = %q
PROFILE_REVISION = %d
PROFILE_ALL_VERIFIED = %s

`, p.Meta.SourceDocument, p.Meta.ID, p.Meta.Revision,
		p.Meta.ID, p.Meta.Revision, pyBool(p.Meta.AllEntriesVerified))

	for _, bomType := range []string{"SBOM", "QBOM", "AIBOM", "HBOM"} {
		fields := p.FieldsForBOMType(bomType)
		if len(fields) == 0 {
			continue
		}
		fmt.Fprintf(&b, "# Render counts from len(%s_FIELDS) — never write the number.\n", bomType)
		fmt.Fprintf(&b, "%s_FIELDS: list[ProfileField] = [\n", bomType)
		for _, f := range fields {
			writePyField(&b, f, "    ")
		}
		b.WriteString("]\n\n")
	}

	b.WriteString(`# TYPE-DISCRIMINATED (CERT-In Table 9). Score each crypto asset against the
# field set for ITS asset_type — see the Go comment for why this matters.
CRYPTO_FIELDS_BY_ASSET_TYPE: dict[str, list[ProfileField]] = {
`)
	for _, name := range p.cryptoTypeNames() {
		t := p.CryptoAsset.Types[name]
		fmt.Fprintf(&b, "    %q: [\n", t.AssetTypeValue)
		for _, f := range t.Fields {
			if f.IsScored() {
				writePyField(&b, f, "        ")
			}
		}
		b.WriteString("    ],\n")
	}
	b.WriteString("}\n\n")

	for _, c := range p.SBOM.MinimumElementCategories {
		if c.Kind != "per_project_settings" {
			continue
		}
		b.WriteString("# CERT-In Table 5 category 3 — per-PROJECT settings, not a report section.\n")
		b.WriteString("PRACTICE_FIELDS: list[ProfileField] = [\n")
		for _, f := range c.SubElements {
			writePyField(&b, f, "    ")
		}
		b.WriteString("]\n\n")
	}

	writePyList(&b, "BOM_LEVELS", levelIDs(p.SBOM.Levels))
	writePyList(&b, "SDLC_CLASSIFICATIONS", levelIDs(p.SBOM.Classifications))
	writePyList(&b, "VEX_STATUSES", vexIDs(p.VEX.Statuses))

	path := filepath.Join(outDir, "generated_certin.py")
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, b.Bytes(), 0o600); err != nil {
		return "", err
	}
	return path, nil
}

func writePyField(b *bytes.Buffer, f Field, indent string) {
	fmt.Fprintf(b, "%sProfileField(%q, %d, %q, %q, %q, %q, %q, %d, %s, %s, %d, %q),\n",
		indent, f.ID, f.Ordinal, f.Name, f.CanonicalPath,
		f.CycloneDXPath, f.SPDXPath, f.Type, f.Weight,
		pyBool(f.Required), pyBool(f.IsScored()), f.SourcePage, f.Status)
}

func writePyList(b *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(b, "%s: list[str] = [\n", name)
	for _, v := range values {
		fmt.Fprintf(b, "    %q,\n", v)
	}
	b.WriteString("]\n\n")
}

func pyBool(v bool) string {
	if v {
		return "True"
	}
	return "False"
}

// SortedKeys is a helper for deterministic emission.
func SortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
