"""The AIBOM operational profile — AxeBOM's own field set, read at runtime.

⚠ THIS IS NOT `AIBOM_FIELDS`, AND THE DIFFERENCE IS THE ENTIRE POINT.

`AIBOM_FIELDS` comes from `generated_certin.py`, is generated from
`docs/reference/certin-v2.0.yaml`, and produces `completeness_pct` and
`declaration_pct` — the two numbers a customer hands to a regulator.

The fields here come from `docs/reference/aibom-operational-v1.yaml`, a
different file with a different authority (ours, not CERT-In's), and produce a
different, separately-labelled number. CERT-In Table 10 describes a MODEL; this
describes the AI SYSTEM around it — the prompts it is given, the vector store
retrieval puts in front of it, the services it calls, and how a person has
classified the whole thing. Merging the two would let a customer's diligence
about vector stores raise a compliance percentage.

⚠ READ AT RUNTIME, AND THE GO SIDE IS GENERATED. Python scores from this file
(the same way `workers/hbom/profile.py` reads its own); Go reads
`model.AIBOMOperationalFields`, generated by `task profile:gen`, because a
service container has no copy of `docs/`. Both come from this one YAML.

⚠ THE COUNT IS NEVER WRITTEN HERE OR ANYWHERE ELSE (invariant 2). It is
whatever the profile says.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

from axebom_shared.normalize.coverage import Field, fields_from_profile

#: Repo-relative, resolved by the caller's working directory — the identical
#: convention `workers/hbom/profile.MANUFACTURING_PROFILE_PATH` uses.
#:
#: ⚠ THE NORMALIZE-CONSUMER IMAGE MUST COPY THIS FILE IN. The CERT-In profile
#: and the HBOM manufacturing profile already are, for exactly this reason;
#: omitting it raises FileNotFoundError on the first AIBOM trigger rather than
#: at build time.
OPERATIONAL_PROFILE_PATH = Path("docs/reference/aibom-operational-v1.yaml")

_SECTION = "aibom_operational"


@lru_cache(maxsize=2)
def _load(path: str) -> dict[str, Any]:
    data = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def operational_profile(path: Path | None = None) -> dict[str, Any]:
    """The parsed operational profile."""
    return _load(str(path or OPERATIONAL_PROFILE_PATH))


def operational_fields(path: Path | None = None) -> list[Field]:
    """The operational field set, scored separately from CERT-In's.

    Built through the SAME `fields_from_profile` the CERT-In path uses, so both
    numbers apply one implementation of weighting and of the `[]` canonical-path
    convention. Two implementations would eventually disagree about what a field
    is worth, and the disagreement would surface as two percentages that cannot
    both be right.
    """
    section = operational_profile(path).get(_SECTION) or {}
    return fields_from_profile(section.get("elements") or [])


def operational_label(path: Path | None = None) -> str:
    """What a report calls this number.

    ⚠ DATA, NOT A STRING IN A RENDERER. A renderer that hardcoded a label could
    print "coverage" next to a number that is not the compliance one, and a
    reader would have no way to tell.
    """
    section = operational_profile(path).get(_SECTION) or {}
    return str(section.get("label") or "AI operational surface")


def operational_meta(path: Path | None = None) -> dict[str, Any]:
    """Identity of the profile this score came from, to store beside the score.

    `is_compliance` travels with the number so no consumer has to know which
    profile ids are compliance standards — the flag is checkable, a naming
    convention is not.
    """
    meta = operational_profile(path).get("profile") or {}
    return {
        "profile_id": str(meta.get("id") or ""),
        "profile_revision": int(meta.get("revision") or 0),
        "label": operational_label(path),
        "is_compliance": str(meta.get("kind") or "compliance") == "compliance",
    }
