// Package vault stores credentials outside the database.
//
// THE RULE THIS PACKAGE EXISTS TO ENFORCE:
// project.repository_connections.credential_ref holds a PATH, never a token.
// If a token string ever lands in that column, a database backup becomes a
// credential dump and every restore, replica and analytics export spreads it.
//
// WHY A HAND-WRITTEN CLIENT rather than github.com/hashicorp/vault/api:
// Vault's KV v2 HTTP API is four endpoints, and the official Go client pulls a
// large dependency tree whose licensing needs review under CLAUDE.md invariant
// 9 (HashiCorp moved Vault itself to BUSL-1.1 in 2023; the api submodule is
// separately licensed, which is exactly the kind of nuance a build should not
// depend on). Four endpoints of documented HTTP is the smaller risk.
//
// THE SUBTLE VULNERABILITY THIS PACKAGE GUARDS AGAINST:
// once a path is stored in a row and later dereferenced, that path is a read
// primitive. The service holds ONE Vault token with access to the whole mount,
// so an attacker who can influence a stored ref — through a mass-assignment
// bug, an import, an admin API, a migration — can read any other tenant's
// secret. Hence: paths are DERIVED server-side from (tenant, kind, id), and
// every read re-derives and compares. A ref that does not match its owner is
// refused before Vault is contacted. See Store.Get.
package vault

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"
)

// ErrNotFound is returned when a secret does not exist.
var ErrNotFound = errors.New("secret not found")

// ErrRefNotOwned is returned when a credential reference does not belong to the
// tenant asking for it.
//
// This is the tenancy check for secrets, and it is separate from RLS: RLS
// protects the ROW that holds the reference, this protects the SECRET the
// reference points at. Both are needed — a bug that leaks a ref string must not
// also leak the credential.
var ErrRefNotOwned = errors.New("credential reference does not belong to this tenant")

// Store is the credential store.
//
// Deliberately small. Anything richer — leases, dynamic credentials, transit
// encryption — is a Phase 16 concern, and a wide interface now would be
// implemented by the test fake in ways that drift from the real one.
type Store interface {
	// Put writes a secret and returns the reference to persist.
	Put(ctx context.Context, ref Ref, data map[string]string) (string, error)
	// Get reads a secret. It must verify the ref belongs to ref.TenantID.
	Get(ctx context.Context, ref Ref, stored string) (map[string]string, error)
	// Delete removes a secret. Deleting an absent secret is not an error.
	Delete(ctx context.Context, ref Ref, stored string) error
	// Ping reports whether the store is reachable, for readiness checks.
	Ping(ctx context.Context) error
}

// Kind names what a secret is for. It becomes a path segment, so the set is
// closed — a free-form string would let a caller construct a path outside its
// tenant's subtree.
type Kind string

const (
	// KindRepoToken is an OAuth or personal access token for a repository
	// connection. Only the fetcher ever reads one (ADR-0008).
	KindRepoToken Kind = "repo-token"
	// KindWebhookSecret is a shared secret for verifying inbound webhooks.
	KindWebhookSecret Kind = "webhook-secret"
)

func (k Kind) valid() bool { return k == KindRepoToken || k == KindWebhookSecret }

// Ref identifies a secret by the facts the SERVER knows, never by a string the
// client supplied.
type Ref struct {
	TenantID string
	Kind     Kind
	// ID is the owning row's primary key — a connection id, for instance.
	ID string
}

// Path derives the logical path for a reference.
//
// Deterministic and tenant-prefixed, which is what makes the ownership check in
// Get possible: the correct path for a ref can always be recomputed, so the
// stored string never has to be trusted.
func (r Ref) Path() (string, error) {
	if err := r.validate(); err != nil {
		return "", err
	}
	return fmt.Sprintf("encorebom/tenants/%s/%s/%s", r.TenantID, r.Kind, r.ID), nil
}

func (r Ref) validate() error {
	switch {
	case !r.Kind.valid():
		return fmt.Errorf("vault: unknown secret kind %q", r.Kind)
	case r.TenantID == "":
		return errors.New("vault: empty tenant id")
	case r.ID == "":
		return errors.New("vault: empty id")
	}
	// Path traversal defence. These ids are UUIDs generated by Postgres, so a
	// separator here means something upstream is wrong — and "something
	// upstream is wrong" is exactly when a traversal reaches Vault.
	for _, s := range []string{r.TenantID, r.ID} {
		if strings.ContainsAny(s, "/\\.%") || strings.ContainsAny(s, "\x00\n\r") {
			return fmt.Errorf("vault: identifier %q contains a path separator or control character", s)
		}
	}
	return nil
}

// checkOwnership verifies a stored reference matches what ref derives to.
func checkOwnership(ref Ref, stored string) (string, error) {
	want, err := ref.Path()
	if err != nil {
		return "", err
	}
	if stored != "" && stored != want {
		// Do NOT include the stored value in the error: it would land in logs,
		// and the whole point is that this path may be attacker-influenced.
		return "", ErrRefNotOwned
	}
	return want, nil
}

// ---------------------------------------------------------------------------
// HTTP client for Vault KV v2
// ---------------------------------------------------------------------------

// Config configures the client.
type Config struct {
	// Address is Vault's base URL, e.g. http://localhost:58200.
	Address string
	// Token authenticates to Vault. In production this comes from a Kubernetes
	// or AppRole login, never a static root token.
	Token string
	// Mount is the KV v2 mount point.
	Mount string
	// Timeout bounds a single request.
	Timeout time.Duration

	HTTPClient *http.Client
}

// Client talks to Vault's KV v2 API.
type Client struct {
	cfg Config
	hc  *http.Client
}

// New builds a client. It does NOT contact Vault — construction must not
// depend on a network round trip, or a Vault restart takes every service with
// it. Reachability is a readiness concern; see Ping.
func New(cfg Config) (*Client, error) {
	if cfg.Address == "" {
		return nil, errors.New("vault: no address configured")
	}
	if cfg.Token == "" {
		return nil, errors.New("vault: no token configured")
	}
	if cfg.Mount == "" {
		cfg.Mount = "secret"
	}
	if cfg.Timeout <= 0 {
		cfg.Timeout = 10 * time.Second
	}
	hc := cfg.HTTPClient
	if hc == nil {
		hc = &http.Client{Timeout: cfg.Timeout}
	}
	cfg.Address = strings.TrimRight(cfg.Address, "/")
	return &Client{cfg: cfg, hc: hc}, nil
}

// Put writes a secret and returns the reference to store in the database.
func (c *Client) Put(ctx context.Context, ref Ref, data map[string]string) (string, error) {
	path, err := ref.Path()
	if err != nil {
		return "", err
	}
	// KV v2 wraps the payload in {"data": {...}}; forgetting the envelope
	// writes a secret whose keys are all wrong and reads back as garbage.
	body, err := json.Marshal(map[string]any{"data": data})
	if err != nil {
		return "", err
	}
	if _, err := c.do(ctx, http.MethodPost, c.dataURL(path), body); err != nil {
		return "", err
	}
	return path, nil
}

// Get reads a secret, refusing a reference that does not belong to ref.TenantID.
func (c *Client) Get(ctx context.Context, ref Ref, stored string) (map[string]string, error) {
	path, err := checkOwnership(ref, stored)
	if err != nil {
		return nil, err
	}

	raw, err := c.do(ctx, http.MethodGet, c.dataURL(path), nil)
	if err != nil {
		return nil, err
	}

	var resp struct {
		Data struct {
			Data map[string]string `json:"data"`
		} `json:"data"`
	}
	if err := json.Unmarshal(raw, &resp); err != nil {
		return nil, fmt.Errorf("vault: unreadable response: %w", err)
	}
	if len(resp.Data.Data) == 0 {
		return nil, ErrNotFound
	}
	return resp.Data.Data, nil
}

// Delete removes a secret.
//
// Uses the `metadata` endpoint, not `data`: deleting through `data` soft-deletes
// the latest version and leaves every prior version readable, so a "deleted"
// token would still be retrievable. For a credential, that is not deletion.
func (c *Client) Delete(ctx context.Context, ref Ref, stored string) error {
	path, err := checkOwnership(ref, stored)
	if err != nil {
		return err
	}
	_, err = c.do(ctx, http.MethodDelete, c.metadataURL(path), nil)
	if errors.Is(err, ErrNotFound) {
		return nil // deleting what is not there is success
	}
	return err
}

// Ping reports whether Vault is reachable and unsealed.
func (c *Client) Ping(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		c.cfg.Address+"/v1/sys/health", nil)
	if err != nil {
		return err
	}
	resp, err := c.hc.Do(req)
	if err != nil {
		return fmt.Errorf("vault unreachable: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	_, _ = io.Copy(io.Discard, io.LimitReader(resp.Body, 4<<10))

	// Vault answers /sys/health with a STATUS CODE, not a body flag: 200
	// initialized+unsealed+active, 429 standby, 501 uninitialized, 503 sealed.
	// A sealed Vault is reachable and useless, so only 200 and 429 are healthy.
	switch resp.StatusCode {
	case http.StatusOK, http.StatusTooManyRequests:
		return nil
	case http.StatusServiceUnavailable:
		return errors.New("vault is sealed")
	default:
		return fmt.Errorf("vault health returned %d", resp.StatusCode)
	}
}

func (c *Client) dataURL(path string) string {
	return fmt.Sprintf("%s/v1/%s/data/%s", c.cfg.Address, c.cfg.Mount, path)
}

func (c *Client) metadataURL(path string) string {
	return fmt.Sprintf("%s/v1/%s/metadata/%s", c.cfg.Address, c.cfg.Mount, path)
}

// do performs a request and normalizes the failure modes.
func (c *Client) do(ctx context.Context, method, url string, body []byte) ([]byte, error) {
	return vaultRequest(ctx, c.hc, c.cfg.Token, method, url, body)
}

// vaultRequest is the shared HTTP path for every Vault mount.
//
// Extracted so the KV and Transit clients cannot diverge on the part that
// matters: the error handling below deliberately drops Vault's response text,
// and a second copy would eventually be written without that.
func vaultRequest(
	ctx context.Context, hc *http.Client, token, method, url string, body []byte,
) ([]byte, error) {
	var rdr io.Reader
	if body != nil {
		rdr = bytes.NewReader(body)
	}
	req, err := http.NewRequestWithContext(ctx, method, url, rdr)
	if err != nil {
		return nil, err
	}
	req.Header.Set("X-Vault-Token", token)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := hc.Do(req)
	if err != nil {
		return nil, fmt.Errorf("vault request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	raw, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, fmt.Errorf("vault: reading response: %w", err)
	}

	switch {
	case resp.StatusCode == http.StatusNotFound:
		return nil, ErrNotFound
	case resp.StatusCode >= 400:
		// Vault echoes the path in some errors. Report the STATUS only — the
		// error text travels into logs, and a secret path in a log is a map
		// for whoever reads it.
		return nil, fmt.Errorf("vault returned %d", resp.StatusCode)
	}
	return raw, nil
}

// ---------------------------------------------------------------------------
// Memory store
// ---------------------------------------------------------------------------

// Memory is an in-process Store for tests.
//
// It enforces the SAME ownership rule as the real client, deliberately: a fake
// that skips the check would let a cross-tenant test pass while the product is
// vulnerable, which is worse than having no test.
type Memory struct {
	mu   sync.Mutex
	data map[string]map[string]string
}

func NewMemory() *Memory {
	return &Memory{data: make(map[string]map[string]string)}
}

func (m *Memory) Put(_ context.Context, ref Ref, data map[string]string) (string, error) {
	path, err := ref.Path()
	if err != nil {
		return "", err
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	cp := make(map[string]string, len(data))
	for k, v := range data {
		cp[k] = v
	}
	m.data[path] = cp
	return path, nil
}

func (m *Memory) Get(_ context.Context, ref Ref, stored string) (map[string]string, error) {
	path, err := checkOwnership(ref, stored)
	if err != nil {
		return nil, err
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	v, ok := m.data[path]
	if !ok {
		return nil, ErrNotFound
	}
	cp := make(map[string]string, len(v))
	for k, val := range v {
		cp[k] = val
	}
	return cp, nil
}

func (m *Memory) Delete(_ context.Context, ref Ref, stored string) error {
	path, err := checkOwnership(ref, stored)
	if err != nil {
		return err
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.data, path)
	return nil
}

func (m *Memory) Ping(context.Context) error { return nil }

// Contains reports whether a raw value appears anywhere in the store. Tests use
// it to assert a token reached Vault and not the database.
func (m *Memory) Contains(value string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	for _, secret := range m.data {
		for _, v := range secret {
			if v == value {
				return true
			}
		}
	}
	return false
}
