// Command scan-orchestrator is the EncoreBOM scan-orchestrator service.
//
// Scan lifecycle: job fan-out, engine tracking, aggregation, progress.
//
// GENERATED by tools/gen-service. The scaffold — wiring, health, shutdown — is
// regenerated; handlers and business logic are hand-written under internal/.
// Re-running the generator will not clobber internal/.
package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"

	"github.com/encorebom/encorebom/libs/go-shared/platform/config"
	"github.com/encorebom/encorebom/libs/go-shared/platform/health"
	"github.com/encorebom/encorebom/libs/go-shared/platform/httpx"
	"github.com/encorebom/encorebom/libs/go-shared/platform/obs"
)

const serviceName = "scan-orchestrator"

// Injected at release time via -ldflags. See cmd/encorebom/version.go for why
// build provenance is load-bearing rather than cosmetic.
var version = "dev"

func main() {
	if err := run(); err != nil {
		// slog may not be configured yet if config loading is what failed.
		fmt.Fprintf(os.Stderr, "%s: %v\n", serviceName, err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.LoadService(serviceName)
	if err != nil {
		return err
	}

	obs.InitLogger(obs.LogConfig{
		Service: serviceName,
		Level:   cfg.LogLevel,
		Format:  cfg.LogFormat,
	})
	slog.Info("starting", "version", version, "config", cfg.String())

	ctx := context.Background()

	shutdownTracer, err := obs.InitTracer(ctx, obs.TraceConfig{
		Service:     serviceName,
		Namespace:   cfg.OTel.Namespace,
		Endpoint:    cfg.OTel.Endpoint,
		Env:         string(cfg.Env),
		SampleRatio: 0.1,
	})
	if err != nil {
		// Telemetry being unavailable must never prevent a service from
		// starting. Degrade loudly, serve traffic.
		slog.Warn("tracing disabled", "cause", err.Error())
		shutdownTracer = func(context.Context) error { return nil }
	}
	defer func() { _ = shutdownTracer(context.Background()) }()

	metrics := obs.NewMetrics(serviceName)

	checker := health.New(serviceName, version)
	registerHealthChecks(checker)

	mux := http.NewServeMux()
	checker.Mount(mux)
	registerRoutes(mux)

	// Catch-all. Without it, ServeMux answers unmatched routes with its own
	// text/plain "404 page not found", which breaks the error contract in
	// docs/02-CONTRACTS.md §9 and gives cross-tenant 404s a different shape
	// from routing 404s — an oracle for probing which ids exist.
	mux.HandleFunc("/", httpx.NotFound)

	handler := httpx.Chain(mux, httpx.Default(metrics, cfg.WriteTimeout)...)

	return httpx.Run(ctx, httpx.ServerConfig{
		Addr:          fmt.Sprintf(":%d", cfg.HTTPPort),
		MetricsAddr:   fmt.Sprintf(":%d", cfg.MetricsPort),
		Handler:       handler,
		Metrics:       metrics,
		ReadTimeout:   cfg.ReadTimeout,
		WriteTimeout:  cfg.WriteTimeout,
		IdleTimeout:   cfg.IdleTimeout,
		ShutdownGrace: cfg.ShutdownGrace,
	})
}
